"""W6.3 — SUMMARY.md generator for the LLM demo recorder.

Boki can paste the markdown directly into a pitch deck. Five archetype
sections + a token totals footer. Deterministic across runs (sorted
archetypes, fixed number formatting).
"""

from __future__ import annotations

from typing import Iterable

from .recorder import DemoRecord


def build_summary_md(records: Iterable[DemoRecord]) -> str:
    rows = sorted(records, key=lambda r: r.archetype)
    n = len(rows)
    if n == 0:
        return "# W6.2 LLM ingest — demo recorder\n\n_(no records)_\n"

    total_input = sum(r.input_tokens for r in rows)
    total_output = sum(r.output_tokens for r in rows)
    total_wall = sum(r.wall_clock_ms for r in rows)
    total_cache_create = sum(r.cache_creation_input_tokens for r in rows)
    total_cache_read = sum(r.cache_read_input_tokens for r in rows)
    mode = rows[0].mode

    lines = [
        "# W6.2 LLM ingest — demo recorder",
        "",
        f"_Mode: **{mode}** — generated by `tools.llm_demo_recorder`._",
        "",
        "## At a glance",
        "",
        "| Archetype | Wall-clock (ms) | Input tok | Output tok | Cache read | GDD sha256[:16] |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r.archetype}` | {r.wall_clock_ms} | {r.input_tokens} | "
            f"{r.output_tokens} | {r.cache_read_input_tokens} | "
            f"`{r.gdd_sha256[:16]}…` |"
        )
    lines.extend([
        f"| **TOTAL** | **{total_wall}** | **{total_input}** | "
        f"**{total_output}** | **{total_cache_read}** | — |",
        "",
        "## Per-archetype detail",
        "",
    ])
    for r in rows:
        lines.extend([
            f"### {r.archetype}",
            "",
            f"- mode: `{r.mode}`",
            f"- model: `{r.model}`",
            f"- wall_clock: `{r.wall_clock_ms}` ms",
            f"- tokens in/out: `{r.input_tokens}` / `{r.output_tokens}`",
            f"- cache create/read: `{r.cache_creation_input_tokens}` / "
            f"`{r.cache_read_input_tokens}`",
            f"- GDD sha256: `{r.gdd_sha256}`",
            "",
            "**Prompt:**",
            "",
            f"> {r.prompt}",
            "",
        ])
    lines.extend([
        "## Token totals",
        "",
        f"- input_tokens_total: **{total_input}**",
        f"- output_tokens_total: **{total_output}**",
        f"- cache_creation_input_tokens_total: **{total_cache_create}**",
        f"- cache_read_input_tokens_total: **{total_cache_read}**",
        f"- wall_clock_ms_total: **{total_wall}**",
        "",
    ])
    return "\n".join(lines) + "\n"
