"""Studio E2E codegen emitter (P5.9)."""
from __future__ import annotations
import json
from dataclasses import dataclass, field
from pathlib import Path
from string import Template
from typing import Any


_PLAYWRIGHT_CONFIG_TS = Template(
    """import { defineConfig, devices } from '@playwright/test';

/**
 * P5.9 — Studio E2E codegen for $slug.
 *
 * `npx playwright test` runs the spec suite against either:
 *   - a static-served Studio scaffold (default: file:// via `serve.cjs`)
 *   - an alternate base URL via STUDIO_BASE_URL env
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: false,
  retries: 0,
  workers: 1,
  use: {
    baseURL: process.env.STUDIO_BASE_URL || 'http://127.0.0.1:8080',
    headless: true,
    actionTimeout: 5_000,
    navigationTimeout: 15_000,
    trace: 'off',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
"""
)


_PACKAGE_JSON = Template(
    """{
  "name": "$crate_name-e2e",
  "private": true,
  "version": "0.1.0",
  "description": "Playwright E2E suite for $slug (P5.9 codegen)",
  "scripts": {
    "test": "playwright test",
    "test:report": "playwright test --reporter=html",
    "serve": "python3 -m http.server 8080 -d ../studio"
  },
  "devDependencies": {
    "@playwright/test": "^1.45.0",
    "typescript": "^5.4.0"
  }
}
"""
)


_TSCONFIG_JSON = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "types": ["node"]
  },
  "include": ["tests/**/*.ts", "playwright.config.ts"]
}
"""


_SPEC_TS = Template(
    """// Auto-generated by P5.9 — DO NOT EDIT BY HAND.
// Studio under test: $slug
import { test, expect } from '@playwright/test';

const STUDIO_PATH = process.env.STUDIO_PATH || '/index.html';

test.describe('Studio · $slug', () => {
  test('loads without console errors', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));
    page.on('console', (msg) => {
      if (msg.type() === 'error') errors.push(msg.text());
    });
    await page.goto(STUDIO_PATH);
    await expect(page).toHaveTitle(/Studio|$slug/i);
    expect(errors).toEqual([]);
  });

  test('spin button advances spin counter', async ({ page }) => {
    await page.goto(STUDIO_PATH);
    const spinBtn = page.getByRole('button', { name: /spin/i });
    await expect(spinBtn).toBeVisible();
    const before = await readSpinCount(page);
    for (let i = 0; i < 5; i++) {
      await spinBtn.click();
    }
    const after = await readSpinCount(page);
    expect(after).toBeGreaterThan(before);
  });

  test('paytable + reel matrix render', async ({ page }) => {
    await page.goto(STUDIO_PATH);
    // Paytable section is generated by W5.4 emitter as <table id="pt">.
    await expect(page.locator('#pt, table.paytable')).toBeVisible();
    // Reel matrix is a <div id="grid"> or .reel-grid container.
    await expect(page.locator('#grid, .reel-grid')).toBeVisible();
  });

  test('rtp ticker has a numeric value', async ({ page }) => {
    await page.goto(STUDIO_PATH);
    // Tick the spin button once to populate the ticker.
    const spinBtn = page.getByRole('button', { name: /spin/i });
    if (await spinBtn.isVisible()) await spinBtn.click();
    const ticker = page.locator('#rtp, .rtp, [data-rtp]');
    if (await ticker.count() > 0) {
      const txt = (await ticker.first().textContent()) || '';
      expect(txt).toMatch(/\\d/);
    }
  });
});

async function readSpinCount(page) {
  // Counter element ID convention: W5.4 emits #spins or [data-spins]
  const el = page.locator('#spins, [data-spins]').first();
  if (!(await el.isVisible())) return 0;
  const txt = (await el.textContent()) || '0';
  const n = parseInt(txt.replace(/[^0-9-]/g, ''), 10);
  return Number.isFinite(n) ? n : 0;
}
"""
)


_README = Template(
    """# $slug — Playwright E2E

Generated by `slot-studio-e2e` (P5.9). The suite verifies the Studio
scaffold emitted by `slot-build --codegen-studio` (W5.4) loads
cleanly, the Spin button advances a spin counter, and the
paytable + reel matrix render.

## Quickstart

```bash
npm install                 # installs @playwright/test + typescript
npx playwright install      # installs Chromium binary (one-off)

# Option A: serve the sibling Studio scaffold via Python
(cd ../studio && python3 -m http.server 8080) &
npm test

# Option B: point at any static-served Studio
STUDIO_BASE_URL=http://localhost:3000 npm test
```

## CI

```yaml
- run: cd <e2e-dir> && npm ci
- run: cd <e2e-dir> && npx playwright install --with-deps chromium
- run: cd <e2e-dir> && npx playwright test --reporter=line
```

## Files

* `tests/$slug.spec.ts` — page-load + spin-button + paytable + rtp specs
* `playwright.config.ts` — chromium-only, headless, env-driven baseURL
* `package.json` / `tsconfig.json` — minimal harness
"""
)


# ─── Public API ────────────────────────────────────────────────────


@dataclass
class E2EArtifacts:
    out_dir: Path
    spec_path: Path
    config_path: Path
    package_json: Path
    tsconfig_json: Path
    readme: Path

    def to_dict(self) -> dict[str, Any]:
        return {
            "out_dir": str(self.out_dir),
            "spec": str(self.spec_path),
            "config": str(self.config_path),
            "package_json": str(self.package_json),
            "tsconfig_json": str(self.tsconfig_json),
            "readme": str(self.readme),
        }


def _safe_slug(slug: str) -> str:
    return "".join(ch if (ch.isalnum() or ch in "-_") else "-" for ch in slug)


def write_studio_e2e(
    out_dir: Path,
    *,
    slug: str,
    studio_url: str | None = None,
) -> E2EArtifacts:
    """Emit a Playwright E2E suite for a Studio scaffold.

    ``out_dir`` becomes the suite root containing:
        ``playwright.config.ts``, ``package.json``, ``tsconfig.json``,
        ``tests/<slug>.spec.ts``, ``README.md``.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "tests").mkdir(exist_ok=True)
    safe_slug = _safe_slug(slug)
    crate_name = safe_slug.lower() or "studio"

    config_path = out_dir / "playwright.config.ts"
    config_path.write_text(_PLAYWRIGHT_CONFIG_TS.substitute(slug=safe_slug))

    package_json = out_dir / "package.json"
    package_json.write_text(_PACKAGE_JSON.substitute(
        crate_name=crate_name, slug=safe_slug,
    ))

    tsconfig_json = out_dir / "tsconfig.json"
    tsconfig_json.write_text(_TSCONFIG_JSON)

    spec_path = out_dir / "tests" / f"{safe_slug}.spec.ts"
    spec_path.write_text(_SPEC_TS.substitute(slug=safe_slug))

    readme = out_dir / "README.md"
    readme.write_text(_README.substitute(slug=safe_slug))

    return E2EArtifacts(
        out_dir=out_dir,
        spec_path=spec_path,
        config_path=config_path,
        package_json=package_json,
        tsconfig_json=tsconfig_json,
        readme=readme,
    )
