"""W7.7 — Live PAR Compiler JS bundle generator."""

from __future__ import annotations

import dataclasses
import hashlib
from pathlib import Path


# The canonical JS runtime is kept as a single string constant so the
# bundle SHA-256 is byte-stable across runs (no f-string interpolation
# of versions / timestamps).
JS_RUNTIME = r"""
// W7.7 — Live PAR Compiler runtime
// Generated by tools.par_compiler_js. Do not edit by hand.

const PAR_COMPILER_VERSION = "1.0.0";

/* ─── Closed-form RTP ─────────────────────────────────────────── */

function closedFormRtp(spec) {
  const reels = spec.reels;
  const paytable = spec.paytable;
  const minMatch = spec.min_match;
  const paylines = spec.paylines;
  const anchor = spec.anchor;
  const R = reels.length;
  const totals = reels.map(r => r.reduce((a, b) => a + b, 0));
  if (totals.some(t => t <= 0)) return { rtp: 0, hitFreq: 0, cv: 0 };
  const pAnchor = reels.map((r, i) => (r[anchor] || 0) / totals[i]);
  let prefix = 1.0;
  let ev = 0.0;
  let ev2 = 0.0;
  let hitProb = 0.0;
  for (let k = 0; k < R; k++) {
    prefix *= pAnchor[k];
    const pExact = (k + 1 === R) ? prefix : prefix * (1.0 - pAnchor[k + 1]);
    const payRow = paytable[anchor] || [];
    const col = k + 1 - minMatch;
    const pay = (col >= 0 && col < payRow.length) ? Math.max(payRow[col], 0) : 0;
    ev += pExact * pay;
    ev2 += pExact * pay * pay;
    if (k + 1 >= minMatch) hitProb += pExact;
  }
  const variance = Math.max(ev2 - ev * ev, 0);
  const cv = ev > 0 ? Math.sqrt(variance) / ev : 0;
  return {
    rtp: ev,
    hitFreq: hitProb * paylines,
    cv: cv,
  };
}

/* ─── Mulberry32 (TS↔Rust parity gate, see W6.4) ─────────────── */

function mulberry32(seed) {
  let t = seed >>> 0;
  return function rand() {
    t = (t + 0x6d2b79f5) >>> 0;
    let x = Math.imul(t ^ (t >>> 15), 1 | t);
    x ^= x + Math.imul(x ^ (x >>> 7), 61 | x);
    return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
  };
}

/* ─── Monte Carlo sanity check ────────────────────────────────── */

function pickWeighted(weights, u) {
  let total = 0;
  for (let i = 0; i < weights.length; i++) total += weights[i];
  let roll = u * total;
  for (let i = 0; i < weights.length; i++) {
    roll -= weights[i];
    if (roll <= 0) return i;
  }
  return weights.length - 1;
}

function runMcSimulation(spec, nSpins, seed) {
  const rng = mulberry32(seed);
  const R = spec.reels.length;
  const denomPerSpin = spec.paylines * spec.bet;
  let totalWin = 0;
  let hits = 0;
  for (let s = 0; s < nSpins; s++) {
    let payout = 0;
    const first = pickWeighted(spec.reels[0], rng());
    if (first === spec.anchor) {
      let run = 1;
      for (let r = 1; r < R; r++) {
        if (pickWeighted(spec.reels[r], rng()) === spec.anchor) run++;
        else break;
      }
      const payRow = spec.paytable[spec.anchor] || [];
      const col = run - spec.min_match;
      if (col >= 0 && col < payRow.length && run >= spec.min_match) {
        payout = Math.max(payRow[col], 0) * spec.paylines * spec.bet;
        hits++;
      }
    } else {
      // not anchor on reel 0 → still consume rng draws for other reels
      // so seed equivalence is preserved across the spin loop.
      for (let r = 1; r < R; r++) rng();
    }
    totalWin += payout;
  }
  return {
    nSpins: nSpins,
    rtp: nSpins > 0 ? totalWin / (denomPerSpin * nSpins) : 0,
    hitFreq: nSpins > 0 ? hits / nSpins : 0,
  };
}

/* ─── Convenience entrypoint ─────────────────────────────────── */

function compileAndEvaluate(spec, opts) {
  opts = opts || {};
  const cf = closedFormRtp(spec);
  const out = {
    closedForm: cf,
  };
  if (opts.mcSpins) {
    out.mc = runMcSimulation(spec, opts.mcSpins, opts.seed || 12345);
  }
  return out;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    PAR_COMPILER_VERSION,
    closedFormRtp,
    mulberry32,
    runMcSimulation,
    compileAndEvaluate,
  };
}
if (typeof window !== "undefined") {
  window.ParCompiler = {
    PAR_COMPILER_VERSION,
    closedFormRtp,
    mulberry32,
    runMcSimulation,
    compileAndEvaluate,
  };
}
"""


@dataclasses.dataclass
class JsBundle:
    js: str
    sha256_hex: str
    n_bytes: int

    def to_dict(self) -> dict:
        return {
            "sha256_hex": self.sha256_hex,
            "n_bytes": self.n_bytes,
        }


def canonical_js_runtime() -> str:
    """Return the exact runtime string used in every bundle.

    Stripped of leading/trailing whitespace so the hash is stable
    across CRLF/LF newlines.
    """
    return JS_RUNTIME.strip("\n")


def build_js_bundle() -> JsBundle:
    js = canonical_js_runtime()
    h = hashlib.sha256(js.encode("utf-8")).hexdigest()
    return JsBundle(js=js, sha256_hex=h, n_bytes=len(js.encode("utf-8")))


# ─── Studio HTML wrapper ────────────────────────────────────────────


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SLOT-MATH-ENGINE — Live PAR Compiler</title>
<style>
:root {{
  --bg: #0e1116; --panel: #161b22; --panel-2: #1b2129;
  --text: #e6e6e6; --muted: #9aa4b2; --accent: #3fb950;
}}
* {{ box-sizing: border-box; }}
body {{ margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       background: var(--bg); color: var(--text); padding: 20px; font-size: 14px; }}
header {{ display: flex; align-items: baseline; gap: 16px; margin-bottom: 16px;
          border-bottom: 1px solid #2d333b; padding-bottom: 12px; }}
header h1 {{ font-size: 18px; font-weight: 600; margin: 0; }}
header .meta {{ color: var(--muted); font-size: 12px; }}
main {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }}
.panel {{ background: var(--panel); border-radius: 6px; padding: 14px; }}
.panel h2 {{ margin: 0 0 8px 0; font-size: 13px; color: var(--muted);
              text-transform: uppercase; letter-spacing: 0.04em; }}
textarea {{ width: 100%; height: 280px; background: var(--bg); color: var(--text);
             border: 1px solid #2d333b; border-radius: 4px; padding: 10px;
             font-family: ui-monospace, "JetBrains Mono", monospace; font-size: 12px; }}
button {{ background: var(--accent); color: #0e1116; border: none; padding: 8px 16px;
          border-radius: 4px; font-weight: 600; cursor: pointer; margin-top: 8px; }}
pre {{ background: var(--bg); padding: 10px; border-radius: 4px;
       border: 1px solid #2d333b; overflow: auto; font-size: 12px; margin: 0; }}
.kpi {{ display: grid; grid-template-columns: 1fr 1fr 1fr;
        gap: 8px; margin-bottom: 12px; }}
.kpi-cell {{ background: var(--panel-2); padding: 10px; border-radius: 4px; }}
.kpi-cell .label {{ color: var(--muted); font-size: 11px; text-transform: uppercase; }}
.kpi-cell .value {{ font-size: 20px; font-weight: 600; margin-top: 2px; }}
.bundle-meta {{ color: var(--muted); font-size: 11px; margin-top: 12px;
                 font-family: ui-monospace, monospace; }}
</style>
</head>
<body>
<header>
  <h1>Live PAR Compiler</h1>
  <span class="meta">deterministic closed-form + Mulberry32 MC · offline-first</span>
</header>
<main>
  <section class="panel">
    <h2>Spec (JSON)</h2>
    <textarea id="spec-input">{default_spec}</textarea>
    <button id="run-btn">Compile + Evaluate</button>
    <div class="bundle-meta">JS runtime SHA-256: {sha256}<br>n_bytes: {n_bytes}</div>
  </section>
  <section class="panel">
    <h2>Result</h2>
    <div class="kpi">
      <div class="kpi-cell"><div class="label">closed RTP</div><div class="value" id="kpi-rtp">—</div></div>
      <div class="kpi-cell"><div class="label">hit freq</div><div class="value" id="kpi-hf">—</div></div>
      <div class="kpi-cell"><div class="label">CV</div><div class="value" id="kpi-cv">—</div></div>
    </div>
    <pre id="result-pre">Click "Compile + Evaluate" to run.</pre>
  </section>
</main>
<script>
{js_runtime}
</script>
<script>
const DEFAULT_SPEC = JSON.parse(document.getElementById("spec-input").value);
function run() {{
  let spec;
  try {{
    spec = JSON.parse(document.getElementById("spec-input").value);
  }} catch (e) {{
    document.getElementById("result-pre").textContent =
      "JSON parse error: " + e.message;
    return;
  }}
  const out = window.ParCompiler.compileAndEvaluate(spec, {{
    mcSpins: 10000, seed: 12345
  }});
  document.getElementById("kpi-rtp").textContent = out.closedForm.rtp.toFixed(6);
  document.getElementById("kpi-hf").textContent = out.closedForm.hitFreq.toFixed(4);
  document.getElementById("kpi-cv").textContent = out.closedForm.cv.toFixed(4);
  document.getElementById("result-pre").textContent =
    JSON.stringify(out, null, 2);
}}
document.getElementById("run-btn").addEventListener("click", run);
run();
</script>
</body>
</html>
"""


_DEFAULT_SPEC_JSON = """{
  "reels": [[4, 6], [4, 6], [4, 6], [4, 6], [4, 6]],
  "paytable": [[1, 4, 10], []],
  "min_match": 3,
  "paylines": 20,
  "bet": 1,
  "anchor": 0
}"""


def build_studio_html() -> tuple[str, JsBundle]:
    bundle = build_js_bundle()
    html = _HTML_TEMPLATE.format(
        default_spec=_DEFAULT_SPEC_JSON,
        sha256=bundle.sha256_hex,
        n_bytes=bundle.n_bytes,
        js_runtime=bundle.js,
    )
    return html, bundle


def write_studio_html(out_path: Path) -> tuple[Path, JsBundle]:
    html, bundle = build_studio_html()
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    return out_path, bundle
