"""W6.2 — LLM-assisted NL → GDD ingestion (Anthropic Claude).

Sibling of W6.1 ``tools.gdd_nl_ingest`` (deterministic regex ingester).
W6.2 calls the Anthropic Claude API with a strict tool-use schema and
compiles the structured JSON response into a canonical GDD YAML that
``tools.math_dsl.spec.parse_spec`` accepts.

Design contract
===============
* Determinism — ``temperature=0`` + ``top_k=1`` + sorted-key JSON +
  deterministic float formatting => same prompt produces a bit-identical
  GDD across runs (modulo a cache hit).
* Offline-safe — when ``ANTHROPIC_API_KEY`` is missing the CLI prints
  a clear fallback message and shells out to the W6.1 deterministic
  ingester.
* Cached — every (prompt, model, schema_version) triple hashes into
  ``reports/gdd-llm-cache/<sha256>.json``.  Cache hits skip the API
  call entirely.
* Prompt caching — the system prompt + few-shot exemplar block are
  marked ``cache_control: ephemeral`` so repeated invocations within
  the 5-minute TTL hit Anthropic's prompt cache.

Public API
==========

>>> from tools.gdd_llm_ingest import generate_gdd
>>> result = generate_gdd("design a 96% RTP wolf-themed lines game",
...                       client=mock_client)
>>> result.gdd_yaml.startswith("# GDD generated by W6.2 LLM ingest")
True
"""

from __future__ import annotations

from tools.gdd_llm_ingest.client import (
    AnthropicShim,
    LLMClientProtocol,
    LLMResponse,
    build_default_client,
)
from tools.gdd_llm_ingest.compile import (
    GddCompileError,
    compile_to_gdd_yaml,
    validate_llm_payload,
)
from tools.gdd_llm_ingest.cache import (
    CACHE_DIR,
    cache_key,
    load_cached,
    save_cached,
)
from tools.gdd_llm_ingest.prompt import (
    DEFAULT_MODEL,
    SCHEMA_VERSION,
    SYSTEM_PROMPT,
    build_messages,
)
from tools.gdd_llm_ingest.schema import GDD_TOOL_SCHEMA

__all__ = [
    "AnthropicShim",
    "CACHE_DIR",
    "DEFAULT_MODEL",
    "GDD_TOOL_SCHEMA",
    "GddCompileError",
    "LLMClientProtocol",
    "LLMResponse",
    "SCHEMA_VERSION",
    "SYSTEM_PROMPT",
    "build_default_client",
    "build_messages",
    "cache_key",
    "compile_to_gdd_yaml",
    "generate_gdd",
    "load_cached",
    "save_cached",
    "validate_llm_payload",
]


def generate_gdd(prompt, *, client=None, model=None, use_cache=True,
                 cache_dir=None):
    """High-level entry: prompt → cached/LLM JSON → validated GDD YAML.

    Imported here (after the leaf-module imports) to avoid circulars.
    """
    from tools.gdd_llm_ingest.ingest import generate_gdd as _impl
    return _impl(
        prompt,
        client=client,
        model=model,
        use_cache=use_cache,
        cache_dir=cache_dir,
    )
