"""Svelte UI codegen — minimal reel-grid + paytable + spin-button shell."""
from __future__ import annotations
import json
import re
import string
from pathlib import Path
from typing import Any


_SLUG_RE = re.compile(r"[^a-z0-9-]+")


def slugify(name: str) -> str:
    cleaned = _SLUG_RE.sub("-", name.strip().lower()).strip("-")
    return cleaned or "game"


_PACKAGE_JSON = string.Template("""\
{
  "name": "${slug}-ui",
  "version": "0.1.0",
  "type": "module",
  "private": true,
  "description": "Svelte UI for ${slug} — auto-generated by W4.6 codegen_svelte",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "svelte": "^4.2.0",
    "vite": "^5.1.0",
    "@sveltejs/kit": "^2.5.0",
    "@sveltejs/adapter-static": "^3.0.0",
    "typescript": "^5.4.0"
  }
}
""")


_SVELTE_CONFIG = """\
import adapter from '@sveltejs/adapter-static';

export default {
  kit: {
    adapter: adapter({
      pages: 'build',
      assets: 'build',
      fallback: 'index.html',
      precompress: false,
      strict: true
    })
  }
};
"""


_VITE_CONFIG = """\
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  server: {
    port: 5173,
    strictPort: false
  }
});
"""


_APP_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>__SLUG__ — slot demo</title>
  %sveltekit.head%
</head>
<body data-sveltekit-preload-data="hover">
  <div style="display: contents">%sveltekit.body%</div>
</body>
</html>
"""


_PAGE_SVELTE = """\
<script lang="ts">
  import { onMount } from 'svelte';

  type IRDoc = {
    meta: Record<string, unknown>;
    topology: { reels: number; rows: number };
    reels: { base: string[][] };
    paytable: { combo: string[]; pays: number }[];
    features: { kind: string }[];
  };

  let ir: IRDoc | null = null;
  let grid: string[][] = [];
  let lastWin: number = 0;
  let totalSpins: number = 0;
  let totalPay: number = 0;

  $: rtp = totalSpins > 0 ? totalPay / totalSpins : 0;

  onMount(async () => {
    const response = await fetch('/ir.json');
    ir = (await response.json()) as IRDoc;
    grid = Array.from({ length: ir.topology.rows }, () =>
      ir!.reels.base.map((s) => s[0] ?? '?'),
    );
  });

  function spin() {
    if (!ir) return;
    const newGrid: string[][] = [];
    for (let r = 0; r < ir.topology.rows; r++) {
      const row: string[] = [];
      for (let c = 0; c < ir.reels.base.length; c++) {
        const strip = ir.reels.base[c];
        row.push(strip[Math.floor(Math.random() * strip.length)]);
      }
      newGrid.push(row);
    }
    grid = newGrid;
    // Naive win calc: longest matching paytable row on top line
    const line = grid[0] || [];
    let win = 0;
    for (const row of ir.paytable) {
      let ok = true;
      for (let i = 0; i < row.combo.length; i++) {
        if (row.combo[i] !== line[i] && row.combo[i] !== '*') {
          ok = false; break;
        }
      }
      if (ok && row.pays > win) win = row.pays;
    }
    lastWin = win;
    totalSpins += 1;
    totalPay += win;
  }
</script>

<main>
  <header>
    <h1>__SLUG__</h1>
    <small>Auto-generated by W4.6 — Svelte UI codegen</small>
  </header>

  {#if ir === null}
    <p>Loading IR…</p>
  {:else}
    <section class="grid">
      {#each grid as row}
        <div class="row">
          {#each row as cell}
            <div class="cell">{cell}</div>
          {/each}
        </div>
      {/each}
    </section>

    <section class="controls">
      <button on:click={spin}>SPIN</button>
      <div class="ticker">
        <span>Last win: <strong>{lastWin}</strong></span>
        <span>Spins: {totalSpins}</span>
        <span>RTP: {(rtp * 100).toFixed(2)}%</span>
      </div>
    </section>

    <section class="paytable">
      <h2>Paytable</h2>
      <ul>
        {#each ir.paytable as row}
          <li><code>{row.combo.join(' ')}</code> → <strong>{row.pays}</strong></li>
        {/each}
      </ul>
    </section>

    {#if ir.features.length > 0}
      <section class="features">
        <h2>Features</h2>
        <ul>
          {#each ir.features as f}
            <li>{f.kind}</li>
          {/each}
        </ul>
      </section>
    {/if}
  {/if}
</main>

<style>
  :global(html, body) { background: #0d1117; color: #c9d1d9; font-family: system-ui; margin: 0; }
  main { max-width: 720px; margin: 0 auto; padding: 24px; }
  header h1 { margin: 0; color: #58a6ff; }
  header small { color: #8b949e; }
  .grid { margin: 20px 0; display: flex; flex-direction: column; gap: 4px; }
  .row { display: flex; gap: 4px; justify-content: center; }
  .cell { background: #161b22; border: 1px solid #30363d; border-radius: 6px;
          width: 56px; height: 56px; display: flex; align-items: center;
          justify-content: center; font-weight: 700; }
  .controls { display: flex; align-items: center; gap: 20px; }
  button { background: #58a6ff; color: #fff; border: 0; padding: 10px 24px;
           border-radius: 8px; font-size: 16px; cursor: pointer; }
  button:hover { filter: brightness(1.1); }
  .ticker { display: flex; gap: 14px; color: #8b949e; }
  .paytable ul, .features ul { padding-left: 18px; }
  code { background: rgba(255,255,255,.04); padding: 1px 6px; border-radius: 4px; }
</style>
"""


_README = string.Template("""\
# ${slug}-ui

Auto-generated Svelte UI for **${slug}** — emitted by
W4.6 `slot-build --codegen-svelte <dir>`.

## Quickstart

```bash
npm install
npm run dev
```

Open <http://localhost:5173>.

## Layout

- `src/routes/+page.svelte` — reel grid + paytable + spin button + RTP ticker
- `static/ir.json` — embedded IR snapshot (client-side fetch)
- `svelte.config.js` — `adapter-static` so the build is deployable offline
- `vite.config.ts` — base Vite + SvelteKit config

## Customization

The page wraps the universal IR shape so any IR emitted by `slot-build`
renders here without code changes. Theme/skin work belongs in
`src/routes/+page.svelte`'s `<style>` block.
""")


def write_svelte_codegen(
    *,
    ir: dict[str, Any],
    out_dir: Path,
    slug: str | None = None,
) -> dict[str, Path]:
    """Emit the <slug>-ui Svelte package layout. Returns role → Path."""
    if slug is None:
        slug = slugify(str(ir.get("meta", {}).get("id") or "game"))
    slug = slugify(slug)
    crate_dir = Path(out_dir) / f"{slug}-ui"
    src_dir = crate_dir / "src"
    routes_dir = src_dir / "routes"
    static_dir = crate_dir / "static"
    for d in (src_dir, routes_dir, static_dir):
        d.mkdir(parents=True, exist_ok=True)

    paths: dict[str, Path] = {}
    paths["crate_dir"] = crate_dir
    paths["package_json"] = crate_dir / "package.json"
    paths["package_json"].write_text(_PACKAGE_JSON.substitute(slug=slug))
    paths["svelte_config"] = crate_dir / "svelte.config.js"
    paths["svelte_config"].write_text(_SVELTE_CONFIG)
    paths["vite_config"] = crate_dir / "vite.config.ts"
    paths["vite_config"].write_text(_VITE_CONFIG)
    paths["app_html"] = src_dir / "app.html"
    paths["app_html"].write_text(_APP_HTML.replace("__SLUG__", slug))
    paths["page_svelte"] = routes_dir / "+page.svelte"
    paths["page_svelte"].write_text(_PAGE_SVELTE.replace("__SLUG__", slug))
    paths["ir_json"] = static_dir / "ir.json"
    paths["ir_json"].write_text(json.dumps(ir, indent=2, sort_keys=True))
    paths["readme"] = crate_dir / "README.md"
    paths["readme"].write_text(_README.substitute(slug=slug))
    return paths
