/**
 * W152 Faza 10.5 — Acceptance golden replay.
 *
 * Loads `reports/acceptance/golden.json` (generated by
 * `scripts/acceptance-golden.mjs`) and re-runs a deterministic subset
 * of the reference fixtures, asserting that RTP / hit-rate / max-win-X
 * match within tolerance. Any drift fails the build — the engineer
 * either has an intentional change (regenerate golden) or a regression.
 *
 * Tolerance budget:
 *   * Deterministic seed → exact RTP byte match. We assert
 *     `Math.abs(replay - golden) < 1e-6` (sample-noise free at the
 *     same seed + spins).
 *   * Hit rate: same exact-match window.
 *   * max-win-X: identical.
 *   * Feature trigger frequency map: identical key set; values
 *     compared via the same exact-match window.
 *
 * Subset rationale:
 *   The full 30-fixture snapshot takes ~13 s to generate. Inside a
 *   per-test vitest run we want < 5 s budget so the gate stays
 *   ergonomic. We pick 8 fixtures that span every evaluator family
 *   (lines / ways / cluster / pay-anywhere / variable-rows / cascade /
 *   feature game / pattern). Operators wanting the full sweep run
 *   `node scripts/acceptance-golden.mjs` locally and compare manually.
 *
 * Skip behaviour: if `reports/acceptance/golden.json` is missing, the
 * spec auto-skips and emits a build-hint test.
 */

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseGameIR } from '../src/ir/index.js';
import { runIRSimulation } from '../src/engine/irSimulator.js';

const REPO_ROOT = join(__dirname, '..');
const GOLDEN_PATH = join(REPO_ROOT, 'reports', 'acceptance', 'golden.json');
const FIXTURES_DIR = join(REPO_ROOT, 'tests', 'fixtures', 'reference');

const SUBSET = [
  'classic-3x3-lines', // lines
  '5x3-243ways', // ways
  'cluster-7x7', // cluster
  'pay-anywhere', // pay-anywhere
  'variable-rows-7reels', // variable-rows
  'cascade-drop', // cascade-drop
  'fs-retrigger', // free-spins feature
  'hnw-classic', // hold & win feature
];

interface Golden {
  seed: number;
  spins: number;
  fixtures: Record<
    string,
    {
      rtp: number;
      hitRate: number;
      maxWinX: number;
      features: Record<string, number | null>;
      error?: string;
    }
  >;
}

const haveGolden = existsSync(GOLDEN_PATH);
const golden: Golden | null = haveGolden
  ? (JSON.parse(readFileSync(GOLDEN_PATH, 'utf-8')) as Golden)
  : null;

const EXACT_TOL = 1e-6;

async function replay(fixtureId: string): Promise<Golden['fixtures'][string]> {
  const raw = readFileSync(join(FIXTURES_DIR, `${fixtureId}.json`), 'utf-8');
  const parsed = parseGameIR(JSON.parse(raw));
  if (!parsed.ok) {
    throw new Error(
      `IR parse failed: ${parsed.issues.map((i) => `${i.path} ${i.message}`).join('; ')}`,
    );
  }
  const res = await runIRSimulation(parsed.ir, {
    spins: golden!.spins,
    seed: golden!.seed,
  });
  const features: Record<string, number | null> = {};
  for (const [k, v] of Object.entries(res.featureTriggerFreqs)) {
    features[k] = Number.isFinite(v) ? v : null;
  }
  return {
    rtp: Number(res.rtp.toFixed(6)),
    hitRate: Number(res.hitRate.toFixed(6)),
    maxWinX: Number(res.maxWinX.toFixed(6)),
    features,
  };
}

describe.skipIf(!haveGolden)(
  'W152 Faza 10.5 — Acceptance golden replay',
  () => {
    for (const fixtureId of SUBSET) {
      it(`${fixtureId}: deterministic RTP + hit-rate + max-win-X`, async () => {
        const ref = golden!.fixtures[fixtureId];
        expect(ref).toBeDefined();
        expect(ref.error).toBeUndefined();
        const replayed = await replay(fixtureId);
        expect(Math.abs(replayed.rtp - ref.rtp)).toBeLessThan(EXACT_TOL);
        expect(Math.abs(replayed.hitRate - ref.hitRate)).toBeLessThan(EXACT_TOL);
        expect(replayed.maxWinX).toBe(ref.maxWinX);
        // Feature trigger frequencies: same key set + same values.
        expect(Object.keys(replayed.features).sort()).toEqual(
          Object.keys(ref.features).sort(),
        );
        for (const k of Object.keys(ref.features)) {
          const a = ref.features[k];
          const b = replayed.features[k];
          if (a === null) {
            expect(b).toBeNull();
          } else {
            expect(b).not.toBeNull();
            expect(Math.abs((b as number) - a)).toBeLessThan(EXACT_TOL);
          }
        }
      }, /* timeout */ 30_000);
    }

    it('golden snapshot covers ≥ 20 fixtures (regression guard)', () => {
      const fixtureCount = Object.keys(golden!.fixtures).filter(
        (k) => !golden!.fixtures[k].error,
      ).length;
      expect(fixtureCount).toBeGreaterThanOrEqual(20);
    });

    it('every SUBSET fixture exists in the golden snapshot', () => {
      for (const id of SUBSET) {
        expect(golden!.fixtures[id]).toBeDefined();
      }
    });
  },
);

describe('Faza 10.5 golden-snapshot build hint', () => {
  it.skipIf(haveGolden)(
    'reports/acceptance/golden.json missing — run `node scripts/acceptance-golden.mjs`',
    () => {
      expect(true).toBe(true);
    },
  );
});
