/**
 * W6.4 — PCG-64 XSL-RR-64 TS↔Rust parity & functional suite.
 *
 * The TS `Pcg64` (src/utils/pcg64.ts) and the Rust `Pcg64Backend`
 * (rust-sim/src/rng.rs) must emit **bit-identical** u64 streams for the
 * same numeric seed. The KAT vector fixture is regenerated by
 *     cargo run --release --bin pcg64_kat_dump \
 *       --seeds 0,1,42,12345,18446744073709551615 \
 *       --count 32 \
 *       --out tests/fixtures/pcg64_kat.json
 * Do NOT "fix" a failure by re-dumping the fixture — investigate which
 * implementation diverged from the spec first.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  Pcg64,
  Pcg64Rng,
  PCG64_MULT,
  PCG64_INC_DEFAULT,
} from "../src/utils/pcg64.js";

interface KatVector {
  /** Decimal string — preserves full u64 range across JSON.parse. */
  seed: string;
  seed_hex: string;
  outputs_u64: string[];
  outputs_f64_unit: number[];
}
interface KatFile {
  generator: string;
  reference: string;
  mult: string;
  inc: string;
  count: number;
  vectors: KatVector[];
}

const KAT_PATH = resolve(__dirname, "fixtures", "pcg64_kat.json");
const kat: KatFile = JSON.parse(readFileSync(KAT_PATH, "utf-8"));

function toHexU64(v: bigint): string {
  return "0x" + v.toString(16).toUpperCase().padStart(16, "0");
}

describe("W6.4 — PCG-64 constants match Rust reference", () => {
  it("multiplier is Steele-Vigna 2021 (ends in ...45)", () => {
    expect(PCG64_MULT.toString(16).toLowerCase()).toBe(
      "2360ed051fc65da44385df649fccef45",
    );
    // Hull-Dobell guard: a ≡ 1 (mod 4) → full period 2^128.
    expect(PCG64_MULT % 4n).toBe(1n);
  });

  it("default increment is odd (PCG stream selector requirement)", () => {
    expect(PCG64_INC_DEFAULT & 1n).toBe(1n);
  });

  it("KAT fixture pins constants byte-for-byte", () => {
    // Rust dumper renders with `format!("0x{:032x}")` — 32 hex chars,
    // lowercase, leading zeros preserved.
    expect(kat.mult.toLowerCase()).toBe(
      "0x" + PCG64_MULT.toString(16).toLowerCase().padStart(32, "0"),
    );
    expect(kat.inc.toLowerCase()).toBe(
      "0x" + PCG64_INC_DEFAULT.toString(16).toLowerCase().padStart(32, "0"),
    );
  });
});

describe("W6.4 — PCG-64 TS↔Rust KAT parity", () => {
  for (const vector of kat.vectors) {
    const seedB = BigInt(vector.seed);
    it(`seed=${vector.seed} emits ${kat.count} bit-identical u64 outputs`, () => {
      const rng = new Pcg64(seedB);
      const actual: string[] = [];
      for (let i = 0; i < kat.count; i++) {
        actual.push(toHexU64(rng.nextU64()));
      }
      expect(actual).toEqual(vector.outputs_u64);
    });

    it(`seed=${vector.seed} f64-unit projection matches Rust`, () => {
      const rng = new Pcg64(seedB);
      // Tolerance is ULP-level — Rust uses `(v >> 11) as f64 * (1 / 2^53)`,
      // we use `Number(v >> 11n) / 2**53`. Both are the same operation on
      // a 53-bit integer, so equality should be exact for all 32 draws.
      for (let i = 0; i < kat.count; i++) {
        const got = rng.nextF64();
        expect(got).toBe(vector.outputs_f64_unit[i]);
      }
    });
  }
});

describe("W6.4 — Pcg64 invariants", () => {
  it("identical seeds produce identical streams", () => {
    const a = new Pcg64(42);
    const b = new Pcg64(42);
    for (let i = 0; i < 64; i++) {
      expect(a.nextU64()).toBe(b.nextU64());
    }
  });

  it("different seeds diverge within first 4 draws", () => {
    const a = new Pcg64(1);
    const b = new Pcg64(2);
    let saw = false;
    for (let i = 0; i < 4; i++) {
      if (a.nextU64() !== b.nextU64()) {
        saw = true;
        break;
      }
    }
    expect(saw).toBe(true);
  });

  it("nextF64 lies in [0, 1)", () => {
    const r = new Pcg64(12345);
    for (let i = 0; i < 256; i++) {
      const v = r.nextF64();
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
  });

  it("nextBoundedU32 stays inside [0, max)", () => {
    const r = new Pcg64(7);
    const max = 17;
    for (let i = 0; i < 2048; i++) {
      const v = r.nextBoundedU32(max);
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(max);
    }
  });

  it("nextBoundedU32(1) is always 0", () => {
    const r = new Pcg64(99);
    for (let i = 0; i < 16; i++) {
      expect(r.nextBoundedU32(1)).toBe(0);
    }
  });

  it("split(nonce) produces independent streams (different first u64)", () => {
    const parent = new Pcg64(0xdeadbeef);
    const c1 = parent.split(1);
    const c2 = parent.split(2);
    expect(c1.nextU64()).not.toBe(c2.nextU64());
  });

  it("seedState returns 4 u64 components masked to 64 bits", () => {
    const r = new Pcg64(0xabcd1234);
    const [s0, s1, i0, i1] = r.seedState();
    expect(s0).toBeLessThanOrEqual((1n << 64n) - 1n);
    expect(s1).toBeLessThanOrEqual((1n << 64n) - 1n);
    expect(i0).toBeLessThanOrEqual((1n << 64n) - 1n);
    expect(i1).toBeLessThanOrEqual((1n << 64n) - 1n);
    // Inc must be odd → low bit of low half is 1.
    expect(i1 & 1n).toBe(1n);
  });

  it("rejects negative numeric seed", () => {
    expect(() => new Pcg64(-1)).toThrow();
  });

  it("rejects non-integer numeric seed", () => {
    expect(() => new Pcg64(0.5)).toThrow();
  });

  it("u64 stream after 1024 draws shows BigCrush-style spread", () => {
    // Light sanity — count zero high-bits across 1024 draws. PCG64 should
    // give roughly 512 ± a few hundred 1-bits in the top nibble of each
    // output; we just check it's not catastrophically biased (e.g. all-zero
    // or all-one), which would indicate the LCG hit its fixed point.
    const r = new Pcg64(13);
    let onesTop4 = 0;
    let draws = 0;
    for (let i = 0; i < 1024; i++) {
      const v = r.nextU64();
      const top4 = Number((v >> 60n) & 0xfn);
      onesTop4 += [...top4.toString(2)].filter((c) => c === "1").length;
      draws++;
    }
    // Expected ≈ 1024*2 = 2048 (each top-4 nibble has 2 set bits on avg).
    // 3σ envelope for 4*1024 Bernoulli(0.5) is ±96 around 2048.
    expect(onesTop4).toBeGreaterThan(1700);
    expect(onesTop4).toBeLessThan(2400);
    expect(draws).toBe(1024);
  });
});

describe("W6.4 — Pcg64Rng high-level facade", () => {
  it("getSeed preserves the constructor seed (masked to u64)", () => {
    const r = new Pcg64Rng(12345);
    expect(r.getSeed()).toBe(12345n);
  });

  it("nextFloat in [0,1) and deterministic", () => {
    const a = new Pcg64Rng(7);
    const b = new Pcg64Rng(7);
    for (let i = 0; i < 32; i++) {
      const x = a.nextFloat();
      const y = b.nextFloat();
      expect(x).toBe(y);
      expect(x).toBeGreaterThanOrEqual(0);
      expect(x).toBeLessThan(1);
    }
  });

  it("nextInt covers [min,max] inclusive", () => {
    const r = new Pcg64Rng(11);
    const seen = new Set<number>();
    for (let i = 0; i < 4096; i++) {
      seen.add(r.nextInt(3, 7));
    }
    expect([...seen].sort()).toEqual([3, 4, 5, 6, 7]);
  });

  it("pick fails on empty array", () => {
    const r = new Pcg64Rng(1);
    expect(() => r.pick([])).toThrow();
  });

  it("chance honors p=0 / p=1 edges deterministically", () => {
    const r = new Pcg64Rng(1);
    expect(r.chance(0)).toBe(false);
    expect(r.chance(1)).toBe(true);
  });

  it("clone resets to initial seed (not current state)", () => {
    const r = new Pcg64Rng(42);
    const v1 = r.nextFloat();
    r.nextFloat();
    r.nextFloat();
    const c = r.clone();
    expect(c.nextFloat()).toBe(v1);
  });
});
