"""W6.3 — HTML/CSS templates for the pitch report.

Pure-stdlib f-strings — no Jinja, no Bottle. Everything in
``pitch.css`` is inline-able and zero-dep; all font references use
generic families (`monospace`, `sans-serif`) so there's no external
`@font-face` fetch.
"""

from __future__ import annotations


PITCH_CSS = """\
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 0 0 60px;
  font-family: -apple-system, "Segoe UI", system-ui, sans-serif;
  color: #1a1a1a;
  background: #fafafa;
}
header.banner {
  background: #0f1d2b;
  color: #f4f4f4;
  padding: 20px 32px;
  border-bottom: 4px solid #c9a04a;
}
header.banner h1 {
  margin: 0;
  font-size: 22px;
  letter-spacing: 0.5px;
}
header.banner .meta {
  margin-top: 6px;
  font-family: monospace;
  font-size: 12px;
  color: #c9a04a;
}
main {
  max-width: 1180px;
  margin: 0 auto;
  padding: 0 24px;
}
section {
  background: #ffffff;
  margin: 18px 0;
  padding: 18px 22px;
  border: 1px solid #e2e2e2;
  border-left: 4px solid #c9a04a;
  border-radius: 4px;
}
section h2 {
  margin: 0 0 12px;
  font-size: 17px;
  color: #0f1d2b;
  border-bottom: 1px solid #e9e9e9;
  padding-bottom: 6px;
}
section h3 {
  margin: 14px 0 8px;
  font-size: 14px;
  color: #0f1d2b;
}
table {
  border-collapse: collapse;
  width: 100%;
  font-family: monospace;
  font-size: 12px;
}
th, td {
  text-align: left;
  padding: 6px 10px;
  border-bottom: 1px solid #ececec;
  vertical-align: top;
}
th { background: #f4f4f4; font-weight: 600; }
tr.pass td { background: #f3faf4; }
tr.fail td { background: #fdecea; }
tr.skip td { background: #fdf5e0; }
tr.missing td { background: #f0f0f0; color: #999; }
.badge {
  display: inline-block;
  padding: 1px 8px;
  font-size: 11px;
  font-weight: 600;
  border-radius: 3px;
  font-family: monospace;
}
.badge.pass { background: #2e7d32; color: white; }
.badge.fail { background: #c62828; color: white; }
.badge.skip { background: #f9a825; color: white; }
.badge.missing { background: #9e9e9e; color: white; }
.codeblock {
  background: #f4f4f4;
  border: 1px solid #ddd;
  border-radius: 3px;
  padding: 8px 12px;
  font-family: monospace;
  font-size: 12px;
  white-space: pre;
  overflow-x: auto;
}
.diagram {
  background: #0f1d2b;
  color: #c9a04a;
  padding: 14px 18px;
  font-family: monospace;
  font-size: 12px;
  white-space: pre;
  border-radius: 4px;
  overflow-x: auto;
}
.cols {
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
}
.cols > div { flex: 1 1 280px; }
.kv {
  font-family: monospace;
  font-size: 12px;
}
.kv .k { color: #555; display: inline-block; min-width: 180px; }
.kv .v { color: #1a1a1a; }
.small { font-size: 11px; color: #555; }
footer.foot {
  text-align: center;
  padding: 20px;
  font-family: monospace;
  font-size: 11px;
  color: #777;
}
.tag-vendor { color: #1a4f8b; }
.tag-greenfield { color: #1b6437; }
.tag-llm { color: #6d3a85; }
.nl-table td { vertical-align: top; }
.nl-prompt {
  font-style: italic;
  color: #555;
  font-size: 12px;
}
"""


def html_head(title: str, css: str, generated_meta: str) -> str:
    return (
        '<!DOCTYPE html>\n'
        '<html lang="en">\n'
        '<head>\n'
        '<meta charset="utf-8"/>\n'
        f'<title>{title}</title>\n'
        '<meta name="generator" content="tools.pitch_report/v1.0"/>\n'
        '<meta name="referrer" content="no-referrer"/>\n'
        f'<style>\n{css}</style>\n'
        '</head>\n'
        '<body>\n'
        '<header class="banner">\n'
        f'  <h1>Slot Math Engine Template — Pitch Report</h1>\n'
        f'  <div class="meta">{generated_meta}</div>\n'
        '</header>\n'
        '<main>\n'
    )


HTML_FOOT = (
    '</main>\n'
    '<footer class="foot">\n'
    '  Generated by tools.pitch_report — single-file, offline-safe, deterministic.\n'
    '</footer>\n'
    '</body>\n'
    '</html>\n'
)
