#!/usr/bin/env python3
"""CE COPY TEST — PAR Report renderer.

Generates a single self-contained HTML report per SWID with Excel-style
tables: meta, paytable, reel sets, sweep results, sign-off summary.

Inputs:
  - out/ce-copy-test.<swid>.ir.json   (canonical IR)
  - reports/sweep/ce-sweep.<swid>.json (multi-bet-mult sweep results)

Output:
  - reports/par-report.<swid>.html

Usage:
  python3 scripts/render_par_report.py [--all | --swid 200-1637-001]
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from html import escape
from pathlib import Path


def html_doc(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{escape(title)}</title>
<style>
  body {{ font-family: -apple-system, system-ui, "Segoe UI", Helvetica, sans-serif;
         color: #1a1a1a; max-width: 1200px; margin: 2em auto; padding: 0 1em; line-height: 1.4; }}
  h1, h2 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
  h1 {{ color: #1a3050; font-size: 1.8em; }}
  h2 {{ color: #2b4d7a; font-size: 1.4em; margin-top: 2em; }}
  h3 {{ color: #2b4d7a; font-size: 1.1em; margin-top: 1.5em; }}
  table {{ border-collapse: collapse; margin: 0.8em 0; font-size: 0.9em; }}
  th, td {{ padding: 4px 10px; border: 1px solid #aaa; text-align: right; }}
  th {{ background: #e8eef5; font-weight: 600; }}
  td.l, th.l {{ text-align: left; }}
  td.sym {{ font-weight: 500; color: #114080; }}
  .ok {{ color: #006400; font-weight: 600; }}
  .warn {{ color: #b07000; font-weight: 600; }}
  .err {{ color: #a01010; font-weight: 600; }}
  .meta {{ background: #f4f8fc; border-left: 4px solid #2b4d7a; padding: 8px 14px;
           margin: 1em 0; font-size: 0.95em; }}
  .footer {{ margin-top: 3em; color: #555; font-size: 0.85em; border-top: 1px solid #ccc;
             padding-top: 1em; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1em; }}
</style>
</head>
<body>
{body}
<div class="footer">
  Generated by CE COPY TEST PAR Report Renderer · {escape(dt.datetime.now().isoformat(timespec="seconds"))}
</div>
</body>
</html>
"""


def status_cell(diff_pct: float, threshold_ok: float = 1.0, threshold_warn: float = 3.0) -> str:
    a = abs(diff_pct)
    if a <= threshold_ok:
        return f'<span class="ok">✅ {diff_pct:+.3f}%</span>'
    if a <= threshold_warn:
        return f'<span class="warn">🟡 {diff_pct:+.3f}%</span>'
    return f'<span class="err">❌ {diff_pct:+.3f}%</span>'


def section_meta(ir: dict) -> str:
    m = ir["meta"]
    rtp_bd = m["rtp_breakdown"]
    rows = [
        ("SWID", m["swid"]),
        ("RTP total (Excel)", f"{m['rtp_total']:.4f}"),
        ("Hold (1 − RTP)", f"{m.get('hold', 1.0 - m['rtp_total']):.4f}"),
        ("Hit frequency", f"{m['hit_frequency_all_line']:.6f}"),
        ("Win frequency", f"{m['win_frequency_all_line']:.6f}"),
        ("Top award", f"{m['top_award']:,}" if isinstance(m.get("top_award"), int) else "?"),
        ("Bet multipliers", ", ".join(str(b) for b in m.get("bet_multipliers", []))),
    ]
    rb_rows = [
        ("Base game", f"{rtp_bd['base_game']:.6f}"),
        ("CE feature (base)", f"{rtp_bd['cash_eruption_from_base']:.6f}"),
        ("Free Spins", f"{rtp_bd['free_spins']:.6f}"),
        ("CE feature (FS)", f"{rtp_bd['cash_eruption_from_fs']:.6f}"),
    ]
    rows_html = "\n".join(
        f'<tr><th class="l">{escape(k)}</th><td class="l">{escape(str(v))}</td></tr>'
        for k, v in rows
    )
    rb_html = "\n".join(
        f'<tr><th class="l">{escape(k)}</th><td>{escape(v)}</td></tr>' for k, v in rb_rows
    )
    return f"""
<h2>1 · Game Specification</h2>
<div class="grid">
<table><caption><b>Meta</b></caption>{rows_html}</table>
<table><caption><b>RTP breakdown (Excel)</b></caption>{rb_html}</table>
</div>
"""


def section_paytable(ir: dict) -> str:
    pt = ir["paytable"]
    rows = []
    for e in pt:
        combo = " · ".join(c for c in e["combo"] if c not in ("--", ""))
        rows.append(
            f"<tr><td class=\"l sym\">{escape(combo)}</td>"
            f"<td>{e['pays']:,}</td>"
            f"<td>{e['pph']:.4f}</td>"
            f"<td>{e['rtp_pct']:.4%}</td></tr>"
        )
    body = "\n".join(rows)
    return f"""
<h2>2 · Base-game Paytable</h2>
<table>
<thead><tr><th class="l">Combination</th><th>Pays</th><th>PPH (per 100k)</th><th>RTP&nbsp;%</th></tr></thead>
<tbody>{body}</tbody>
</table>
"""


def section_fs_paytable(ir: dict) -> str:
    pt = ir["fs_paytable"]
    rows = []
    for e in pt:
        combo = " · ".join(c for c in e["combo"] if c not in ("--", "", None))
        rows.append(
            f"<tr><td class=\"l sym\">{escape(combo)}</td>"
            f"<td>{e['pays']:,}</td>"
            f"<td>{e['pph']:.4f}</td>"
            f"<td>{e['rtp_pct']:.4%}</td></tr>"
        )
    body = "\n".join(rows)
    bs = ir.get("bonus_summary", {})
    return f"""
<h2>3 · Free Spins Paytable</h2>
<p>Avg # FS = <b>{bs.get('avg_free_spins', '?'):.4f}</b> ·
   Single-spin payback = <b>{bs.get('single_spin_payback_pct', 0):.4%}</b> ·
   Total payback = <b>{bs.get('total_payback_pct', 0):.4%}</b></p>
<table>
<thead><tr><th class="l">Combination</th><th>Pays</th><th>PPH (per 100k)</th><th>RTP&nbsp;%</th></tr></thead>
<tbody>{body}</tbody>
</table>
"""


def section_symbol_counts(ir: dict) -> str:
    """Render the per-reel symbol count table from IR `symbol_counts_per_reel`
    (dict[symbol → [count_reel1, .., count_reel5])."""
    sc = ir.get("symbol_counts_per_reel", {})
    if not sc:
        return ""
    symbols = list(sc.keys())
    n_reels = max(len(v) for v in sc.values())
    header = "<tr><th class=\"l\">Symbol</th>" + "".join(
        f"<th>Reel {i+1}</th>" for i in range(n_reels)
    ) + "</tr>"
    rows = []
    for sym in symbols:
        cells = [f'<td class="l sym">{escape(sym)}</td>']
        for i in range(n_reels):
            v = sc[sym][i] if i < len(sc[sym]) else 0
            cells.append(f"<td>{v:,.2f}</td>")
        rows.append("<tr>" + "".join(cells) + "</tr>")
    body = "\n".join(rows)
    return f"""
<h2>4 · Base-game Symbol Counts per Reel (mean row-2 exposure, weighted)</h2>
<table>{header}{body}</table>
"""


def section_sweep(sweep: list[dict], excel_rtp_total: float) -> str:
    rows = []
    for r in sweep:
        rows.append(
            "<tr>"
            f"<td>{r['bet_mult']}</td>"
            f"<td>{r['spins']:,}</td>"
            f"<td>{r['base_rtp_sim']:.6f}</td>"
            f"<td>{r['ce_base_rtp_sim']:.6f} <br><small>(excel {r['ce_base_rtp_excel']:.6f})</small></td>"
            f"<td>{r['fs_lines_rtp_sim']:.6f}</td>"
            f"<td>{r['fs_bv_rtp_sim']:.6f}</td>"
            f"<td>{r['ce_fs_rtp_sim']:.6f} <br><small>(excel {r['ce_fs_rtp_excel']:.6f})</small></td>"
            f"<td><b>{r['total_rtp_sim']:.6f}</b></td>"
            f"<td>{status_cell(r['total_diff_pct'])}</td>"
            f"<td>{r['fs_trigger_1_in']:.2f}</td>"
            f"<td>{r['ce_base_trigger_1_in']:.2f}</td>"
            f"<td>{r['ce_fs_trigger_1_in']:.2f}</td>"
            f"<td>{r['grand_hits']:,}</td>"
            "</tr>"
        )
    body = "\n".join(rows)
    avg_total = sum(r["total_rtp_sim"] for r in sweep) / len(sweep)
    max_diff = max(abs(r["total_diff_pct"]) for r in sweep)
    return f"""
<h2>5 · Multi-bet-multiplier Sweep ({len(sweep)} bet multipliers, Monte-Carlo)</h2>
<div class="meta">
  Avg total RTP across all bms = <b>{avg_total:.6f}</b> · Excel target =
  <b>{excel_rtp_total:.6f}</b> · Max |Δ%| over all bms = <b>{max_diff:.2f}%</b>
</div>
<table>
<thead>
<tr>
  <th>Bet&nbsp;mult</th><th>Spins</th><th>Base&nbsp;RTP</th><th>CE&nbsp;base</th>
  <th>FS&nbsp;lines</th><th>FS&nbsp;BV</th><th>CE&nbsp;FS</th><th>Total&nbsp;sim</th>
  <th>Total Δ%</th><th>FS&nbsp;1in</th><th>CEb&nbsp;1in</th><th>CEf&nbsp;1in</th><th>GRAND</th>
</tr>
</thead>
<tbody>{body}</tbody>
</table>
"""


def section_signoff(swid: str, sweep: list[dict], excel_rtp_total: float) -> str:
    n = len(sweep)
    pass_count = sum(1 for r in sweep if abs(r["total_diff_pct"]) <= 3.0)
    avg_total = sum(r["total_rtp_sim"] for r in sweep) / n
    max_diff = max(abs(r["total_diff_pct"]) for r in sweep)
    trigger_metrics = ["fs_trigger_1_in", "ce_base_trigger_1_in", "ce_fs_trigger_1_in"]
    trigger_ok = all(
        abs(r[m] - (139.9 if m == "fs_trigger_1_in"
                   else 120.8 if m == "ce_base_trigger_1_in"
                   else 468.99)) / (139.9 if m == "fs_trigger_1_in"
                   else 120.8 if m == "ce_base_trigger_1_in"
                   else 468.99) * 100 <= 1.0
        for r in sweep for m in trigger_metrics
    )
    return f"""
<h2>6 · Sign-off Summary</h2>
<table>
<tr><th class="l">SWID</th><td class="l"><b>{escape(swid)}</b></td></tr>
<tr><th class="l">Excel target RTP</th><td>{excel_rtp_total:.6f}</td></tr>
<tr><th class="l">Sim avg total RTP</th><td>{avg_total:.6f}</td></tr>
<tr><th class="l">Max |Δ%| across all bms</th><td>{max_diff:.3f} %</td></tr>
<tr><th class="l">Bet mults passed (|Δ%| ≤ 3.0)</th><td>{pass_count} / {n}</td></tr>
<tr><th class="l">Trigger frequencies (all bms ≤ 1.0% off)</th>
    <td>{"✅ PASS" if trigger_ok else "🟡 see sweep table"}</td></tr>
<tr><th class="l">Verdict</th>
    <td><b>{"✅ ACCEPTANCE — within ≤3% tolerance for all 21 bet multipliers" if pass_count == n
            else f"🟡 PARTIAL — {pass_count}/{n} bet multipliers within 3% tolerance"}</b></td></tr>
</table>
"""


def render_report(swid: str, project_root: Path) -> Path:
    ir_path = project_root / "out" / f"ce-copy-test.{swid}.ir.json"
    sweep_path = project_root / "reports" / "sweep" / f"ce-sweep.{swid}.json"
    if not ir_path.exists():
        sys.exit(f"missing IR: {ir_path}")
    if not sweep_path.exists():
        sys.exit(f"missing sweep: {sweep_path} — run `ce-sweep --ir {ir_path} --out reports/sweep`")
    ir = json.loads(ir_path.read_text())
    sweep = json.loads(sweep_path.read_text())
    excel_rtp = ir["meta"]["rtp_total"]
    sections = [
        f'<h1>CE COPY TEST — PAR Report · {escape(swid)}</h1>',
        '<div class="meta">'
        f'1:1 paymodel klon Pattern-CE-a · Excel target RTP <b>{excel_rtp:.4f}</b> · '
        f'Sim avg over {len(sweep)} bms = <b>{sum(r["total_rtp_sim"] for r in sweep)/len(sweep):.6f}</b>'
        '</div>',
        section_meta(ir),
        section_paytable(ir),
        section_fs_paytable(ir),
        section_symbol_counts(ir),
        section_sweep(sweep, excel_rtp),
        section_signoff(swid, sweep, excel_rtp),
    ]
    out_dir = project_root / "reports"
    out_path = out_dir / f"par-report.{swid}.html"
    out_path.write_text(html_doc(f"CE COPY TEST PAR · {swid}", "\n".join(sections)))
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true", help="render all 3 SWIDs")
    ap.add_argument("--swid", help="single SWID, e.g. 200-1637-001")
    args = ap.parse_args()
    project_root = Path(__file__).resolve().parent.parent  # games/ce-copy-test
    swids = (
        ["200-1637-001", "200-1637-002", "200-1637-003"]
        if args.all
        else [args.swid or "200-1637-001"]
    )
    for s in swids:
        p = render_report(s, project_root)
        print(f"  wrote {p}")


if __name__ == "__main__":
    main()
