// CORTI W207-MOBILE — Android entry point (placeholder).
//
// Real implementation is generated by `npx cap add android` from
// mobile/capacitor.config.json. This skeleton exists so reviewers
// can see how the WebView is bridged via the Capacitor BridgeActivity.

package com.vanvinkl.slotstudio;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Plugins are registered automatically via the
        // capacitor.plugins.json descriptor produced by `npx cap sync`.
        // No explicit registerPlugin() calls are required for the
        // bundled Haptics / Share / StatusBar / SplashScreen / Keyboard /
        // Filesystem plugins listed in mobile/capacitor.config.json.
    }
}
