/**
 * W211 Agent B — Demo storyboard registry.
 *
 * Three storyboards (30s elevator / 5min deep / 90min boardroom)
 * authored as static text blocks. The registry lets tests + UI iterate
 * over them in a canonical order. Markdown is generated by `renderStoryboardMd()`
 * and rendered into the deck UI by `renderStoryboardHtml()`.
 */

import { storyboard as elevator } from './storyboard-30sec-elevator.js';
import { storyboard as deep } from './storyboard-5min-deep.js';
import { storyboard as board } from './storyboard-90min-board.js';

export interface StoryboardScene {
  /** "00:00" / "T+0s" / "Slide 12" — time or position cue. */
  cue: string;
  /** What's on screen / in the room. */
  visual: string;
  /** Spoken or dialog line. */
  dialogue: string;
  /** ASCII frame placeholder. */
  ascii?: string;
}

export interface Storyboard {
  /** Slug — also used as the markdown filename anchor. */
  slug: string;
  /** Display name. */
  title: string;
  /** Audience this storyboard targets. */
  audience: string;
  /** Run-time. */
  duration: string;
  /** Goal of the demo. */
  goal: string;
  /** Ordered scenes. */
  scenes: StoryboardScene[];
  /** Audience Q&A bullets pre-empted. */
  qa: string[];
}

export const STORYBOARDS: readonly Storyboard[] = [elevator, deep, board] as const;

export function renderStoryboardMd(s: Storyboard): string {
  const head = [
    `# ${s.title}`,
    '',
    `**Audience:** ${s.audience}`,
    `**Duration:** ${s.duration}`,
    `**Goal:** ${s.goal}`,
    '',
    '## Scenes',
    '',
  ].join('\n');
  const scenes = s.scenes
    .map((sc, i) => {
      const ascii = sc.ascii ? `\n\n\`\`\`\n${sc.ascii}\n\`\`\`` : '';
      return `### ${i + 1}. ${sc.cue}\n\n**Visual:** ${sc.visual}\n\n**Dialogue:** ${sc.dialogue}${ascii}`;
    })
    .join('\n\n');
  const qa = s.qa.length
    ? `\n\n## Pre-empted Q&A\n\n${s.qa.map((q) => `- ${q}`).join('\n')}\n`
    : '';
  return `${head}${scenes}${qa}`;
}

export function renderStoryboardHtml(s: Storyboard): string {
  const scenes = s.scenes
    .map(
      (sc, i) => `<div class="lw-sb-scene">
  <div class="lw-sb-cue">${escapeHtml(`${i + 1}. ${sc.cue}`)}</div>
  <div class="lw-sb-visual"><strong>Visual:</strong> ${escapeHtml(sc.visual)}</div>
  <div class="lw-sb-dialogue"><strong>Dialogue:</strong> ${escapeHtml(sc.dialogue)}</div>
  ${sc.ascii ? `<pre class="lw-sb-ascii">${escapeHtml(sc.ascii)}</pre>` : ''}
</div>`,
    )
    .join('\n');
  const qa = s.qa.length
    ? `<div class="lw-sb-qa"><h4>Pre-empted Q&amp;A</h4><ul>${s.qa.map((q) => `<li>${escapeHtml(q)}</li>`).join('')}</ul></div>`
    : '';
  return `<article class="lw-storyboard" id="lw-sb-${s.slug}">
  <header class="lw-sb-head">
    <h3>${escapeHtml(s.title)}</h3>
    <div class="lw-sb-meta">${escapeHtml(s.audience)} · ${escapeHtml(s.duration)}</div>
    <div class="lw-sb-goal">Goal: ${escapeHtml(s.goal)}</div>
  </header>
  <div class="lw-sb-scenes">${scenes}</div>
  ${qa}
</article>`;
}

function escapeHtml(s: string): string {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
