//! W152 P0-4 — integration tests for the `rng_submission` binary.
//!
//! These tests rebuild the binary on demand (cheap after the first run),
//! invoke it against a temporary directory, and verify:
//!
//!   * Each backend produces a dump file of the requested size.
//!   * The manifest references every produced file.
//!   * Each `.bin` actually hashes to the sha256 written in the manifest.
//!   * The top-level `manifest.sha256` matches the recomputed digest of
//!     `manifest.json` (tamper-evidence).
//!   * Hardware report contains the expected fields.
//!   * Re-running with the same seed yields byte-identical output
//!     (deterministic replay — GLI-19 §3.3.2 requirement).
//!
//! NOTE: these tests use small byte counts (64 KiB per backend) so each
//! pass stays well under 1 s wall-clock on CI. Real cert bundles
//! generated by `scripts/cert-bundle.sh` use 12 MiB per backend.

use serde_json::Value;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;

const BYTES_PER_BACKEND: &str = "65536"; // 64 KiB — fast CI smoke
const TEST_SEED: &str = "12345";

/// Build the binary once and return its absolute path.
fn build_binary() -> PathBuf {
    // Workspace target/ is at REPO/target — this test runs from rust-sim/.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().expect("workspace root");

    let status = Command::new("cargo")
        .current_dir(&manifest_dir)
        .args(["build", "--quiet", "--bin", "rng_submission"])
        .status()
        .expect("cargo build status");
    assert!(status.success(), "cargo build failed");

    let bin = workspace_root.join("target").join("debug").join("rng_submission");
    assert!(bin.exists(), "binary missing at {}", bin.display());
    bin
}

/// Run the binary into a fresh temp dir and return its path.
fn run_into_tmp(bin: &Path, suffix: &str) -> PathBuf {
    let tmp = std::env::temp_dir().join(format!(
        "slot-math-rng-submission-test-{}-{}",
        suffix,
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);

    let status = Command::new(bin)
        .args([
            "--out",
            tmp.to_str().expect("utf-8"),
            "--bytes-per",
            BYTES_PER_BACKEND,
            "--seed",
            TEST_SEED,
        ])
        .status()
        .expect("rng_submission status");
    assert!(status.success(), "rng_submission failed");

    tmp
}

fn hex_sha256(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn bundle_contains_all_five_backend_dumps() {
    let bin = build_binary();
    let out = run_into_tmp(&bin, "all-five");

    for name in ["mulberry32", "pcg64", "xoshiro256ss", "philox4x32", "chacha20"] {
        let path = out.join(format!("{name}-1MiB.bin"));
        let meta = std::fs::metadata(&path)
            .unwrap_or_else(|_| panic!("expected dump file: {}", path.display()));
        assert_eq!(meta.len(), 65536, "{name}: wrong byte count");
    }

    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn manifest_references_every_dump_and_digests_match() {
    let bin = build_binary();
    let out = run_into_tmp(&bin, "manifest-match");

    let manifest_json = std::fs::read(out.join("manifest.json")).expect("manifest.json");
    let manifest: Value = serde_json::from_slice(&manifest_json).expect("manifest parse");

    let artifacts = manifest["artifacts"]
        .as_array()
        .expect("artifacts is array");
    assert_eq!(artifacts.len(), 5, "expected 5 backends");

    for art in artifacts {
        let file = art["file"].as_str().expect("file str");
        let claimed_sha = art["sha256"].as_str().expect("sha256 str");

        let bytes = std::fs::read(out.join(file))
            .unwrap_or_else(|_| panic!("read {file}"));
        let actual_sha = hex_sha256(&bytes);
        assert_eq!(actual_sha, claimed_sha, "digest mismatch for {file}");
    }

    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn manifest_sha_file_matches_recomputed_digest() {
    let bin = build_binary();
    let out = run_into_tmp(&bin, "manifest-sha");

    let manifest_bytes = std::fs::read(out.join("manifest.json")).expect("manifest.json");
    let recomputed = hex_sha256(&manifest_bytes);

    let line = std::fs::read_to_string(out.join("manifest.sha256")).expect("manifest.sha256");
    // Format: "<hex>  manifest.json\n"
    let claimed = line.split_whitespace().next().expect("sha hex");
    assert_eq!(recomputed, claimed, "manifest digest mismatch");

    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn hardware_report_contains_expected_fields() {
    let bin = build_binary();
    let out = run_into_tmp(&bin, "hardware");

    let hw_json = std::fs::read(out.join("hardware.json")).expect("hardware.json");
    let hw: Value = serde_json::from_slice(&hw_json).expect("hardware parse");

    for key in ["os", "arch", "cpu", "rng_submission_version"] {
        assert!(hw.get(key).is_some(), "missing field: {key}");
    }
    // Sanity: not empty.
    assert!(!hw["os"].as_str().unwrap_or("").is_empty(), "os empty");
    assert!(!hw["arch"].as_str().unwrap_or("").is_empty(), "arch empty");

    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn deterministic_replay_two_runs_same_seed() {
    let bin = build_binary();
    let a = run_into_tmp(&bin, "det-a");
    let b = run_into_tmp(&bin, "det-b");

    // Compare every .bin byte-for-byte. Two runs with identical args
    // MUST produce identical bytes (GLI-19 §3.3.2).
    for name in ["mulberry32", "pcg64", "xoshiro256ss", "philox4x32", "chacha20"] {
        let fa = a.join(format!("{name}-1MiB.bin"));
        let fb = b.join(format!("{name}-1MiB.bin"));
        let da = std::fs::read(&fa).expect("read a");
        let db = std::fs::read(&fb).expect("read b");
        assert_eq!(da, db, "{name}: non-deterministic between runs!");
    }

    // Manifest sha256 maps must also be identical (file paths excluded).
    let ma: Value =
        serde_json::from_slice(&std::fs::read(a.join("manifest.json")).unwrap()).unwrap();
    let mb: Value =
        serde_json::from_slice(&std::fs::read(b.join("manifest.json")).unwrap()).unwrap();
    let sa = &ma["sha256_map"];
    let sb = &mb["sha256_map"];
    assert_eq!(sa, sb, "sha256_map differs between identical-seed runs");

    let _ = std::fs::remove_dir_all(&a);
    let _ = std::fs::remove_dir_all(&b);
}

#[test]
fn wave_and_bundle_version_pinned() {
    let bin = build_binary();
    let out = run_into_tmp(&bin, "version");

    let m: Value =
        serde_json::from_slice(&std::fs::read(out.join("manifest.json")).unwrap()).unwrap();

    assert_eq!(
        m["wave"].as_str(),
        Some("W152-P0-4"),
        "wave tag must be W152-P0-4 (tracks master TODO)"
    );
    assert_eq!(
        m["bundle_version"].as_str(),
        Some("1.0.0"),
        "bundle_version must be 1.0.0 (bump only on schema change)"
    );

    let _ = std::fs::remove_dir_all(&out);
}
