"""Vendor onboarding wizard — scaffold → synth PAR → IR → cert."""
from __future__ import annotations
import hashlib
import json
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from tools.vendor_profiles.scaffold import scaffold_profile
from tools.slot_build.cert_xml_v2 import emit_cert_xml_v2, ir_digest


@dataclass
class OnboardStep:
    name: str
    ok: bool
    detail: str = ""
    artifact: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "ok": self.ok,
            "detail": self.detail,
            "artifact": self.artifact,
        }


@dataclass
class OnboardReport:
    vendor_id: str
    out_dir: str
    generated_at_utc: str = ""
    steps: list[OnboardStep] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return all(s.ok for s in self.steps)

    def to_dict(self) -> dict[str, Any]:
        return {
            "vendor_id": self.vendor_id,
            "out_dir": self.out_dir,
            "generated_at_utc": self.generated_at_utc,
            "passed": self.passed,
            "steps": [s.to_dict() for s in self.steps],
        }


def _now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def _synthesize_ir(
    *, vendor_id: str, display_name: str, reels: int, rows: int,
    features: list[str], target_rtp: float,
) -> dict[str, Any]:
    """Build a minimal but structurally-valid universal IR for the
    pilot. This stands in for `parse_par` until the vendor provides
    a real PAR sheet — once they do, the wizard re-runs with
    `parse_par` instead of this synthesizer."""
    return {
        "meta": {
            "id": f"{vendor_id}_pilot",
            "vendor": vendor_id,
            "vendor_name": display_name,
            "swid": f"{vendor_id.upper()}-PILOT-0001",
            "target_rtp": target_rtp,
            "volatility": "medium",
            "version": "1.0.0",
            "notes": [
                f"Auto-generated by W59 vendor-onboard wizard at {_now_utc()}",
                "Replace this IR with real PAR-derived IR before cert.",
            ],
        },
        "topology": {
            "kind": "rectangular",
            "reels": reels,
            "rows": rows,
        },
        "reels": {
            "base": [
                ["A", "B", "C", "D", "E"] * 2 for _ in range(reels)
            ]
        },
        "paytable": [
            {"combo": ["A"] * reels, "pays": 1000},
            {"combo": ["B"] * reels, "pays": 250},
            {"combo": ["C"] * reels, "pays": 100},
        ],
        "features": [{"kind": k} for k in features],
    }


def run_onboarding(
    *,
    vendor_id: str,
    display_name: str,
    out_dir: Path,
    topology: str = "rectangular",
    reels: int = 5,
    rows: int = 3,
    paylines: int = 25,
    features: list[str] | None = None,
    target_rtp: float = 0.96,
    emit_cert: bool = True,
) -> OnboardReport:
    out_dir = Path(out_dir)
    pilot_dir = out_dir / f"pilot_{vendor_id}"
    pilot_dir.mkdir(parents=True, exist_ok=True)

    report = OnboardReport(
        vendor_id=vendor_id,
        out_dir=str(pilot_dir),
        generated_at_utc=_now_utc(),
    )
    features = list(features or ["free_spins", "wild_expand"])

    # ─── Step 1: Profile scaffolding ─────────────────────────────
    try:
        yaml_text = scaffold_profile(
            vendor_id=vendor_id,
            display_name=display_name,
            topology=topology,
            reels=reels,
            rows=rows,
            paylines=paylines,
            features=features,
        )
        profile_path = pilot_dir / f"{vendor_id}.profile.yaml"
        profile_path.write_text(yaml_text)
        report.steps.append(OnboardStep(
            name="scaffold_profile", ok=True,
            detail=f"{len(yaml_text)} bytes",
            artifact=str(profile_path.relative_to(pilot_dir)),
        ))
    except Exception as e:  # noqa: BLE001
        report.steps.append(OnboardStep(
            name="scaffold_profile", ok=False, detail=str(e),
        ))

    # ─── Step 2: Synthesized IR (stand-in PAR) ───────────────────
    try:
        ir = _synthesize_ir(
            vendor_id=vendor_id, display_name=display_name,
            reels=reels, rows=rows, features=features,
            target_rtp=target_rtp,
        )
        ir_path = pilot_dir / "ir.json"
        ir_path.write_text(json.dumps(ir, indent=2, sort_keys=True))
        report.steps.append(OnboardStep(
            name="synthesize_ir", ok=True,
            detail=(
                f"{len(ir.get('paytable') or [])} paytable rows, "
                f"{len(features)} features"
            ),
            artifact=str(ir_path.relative_to(pilot_dir)),
        ))
    except Exception as e:  # noqa: BLE001
        report.steps.append(OnboardStep(
            name="synthesize_ir", ok=False, detail=str(e),
        ))
        ir = None

    # ─── Step 3: IR round-trip digest ────────────────────────────
    try:
        digest = ir_digest(ir) if ir else ""
        # Re-load + recompute to prove deterministic round-trip
        ir2 = json.loads((pilot_dir / "ir.json").read_text())
        digest2 = ir_digest(ir2)
        if digest and digest == digest2:
            report.steps.append(OnboardStep(
                name="ir_roundtrip", ok=True,
                detail=f"digest sha256={digest[:16]}…",
                artifact="ir.json",
            ))
        else:
            report.steps.append(OnboardStep(
                name="ir_roundtrip", ok=False,
                detail=f"digest mismatch {digest[:8]} vs {digest2[:8]}",
            ))
    except Exception as e:  # noqa: BLE001
        report.steps.append(OnboardStep(
            name="ir_roundtrip", ok=False, detail=str(e),
        ))

    # ─── Step 4: Cert XML v2 (optional) ──────────────────────────
    if emit_cert and ir is not None:
        try:
            cert_path = pilot_dir / "cert.v2.xml"
            emit_cert_xml_v2(
                ir, cert_path, mc_report=None,
                provenance={
                    "ir_sha256": ir_digest(ir),
                    "par_merkle_root": "",
                    "signature": "",
                },
            )
            report.steps.append(OnboardStep(
                name="emit_cert_xml_v2", ok=cert_path.exists()
                                          and cert_path.stat().st_size > 0,
                detail=f"{cert_path.stat().st_size} bytes",
                artifact=str(cert_path.relative_to(pilot_dir)),
            ))
        except Exception as e:  # noqa: BLE001
            report.steps.append(OnboardStep(
                name="emit_cert_xml_v2", ok=False, detail=str(e),
            ))

    # ─── Step 5: Bundle manifest ─────────────────────────────────
    try:
        files = sorted(p for p in pilot_dir.iterdir() if p.is_file())
        manifest = {
            "vendor_id": vendor_id,
            "generated_at_utc": report.generated_at_utc,
            "files": [
                {
                    "name": p.name,
                    "size_bytes": p.stat().st_size,
                    "sha256": hashlib.sha256(p.read_bytes()).hexdigest(),
                }
                for p in files
            ],
        }
        (pilot_dir / "MANIFEST.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True)
        )
        report.steps.append(OnboardStep(
            name="manifest", ok=True,
            detail=f"{len(files)} files",
            artifact="MANIFEST.json",
        ))
    except Exception as e:  # noqa: BLE001
        report.steps.append(OnboardStep(
            name="manifest", ok=False, detail=str(e),
        ))

    # ─── Step 6: ONBOARD_REPORT.md ───────────────────────────────
    try:
        md_path = pilot_dir / "ONBOARD_REPORT.md"
        md_path.write_text(render_report_md(report))
        report.steps.append(OnboardStep(
            name="render_report", ok=True,
            detail=f"{md_path.stat().st_size} bytes",
            artifact="ONBOARD_REPORT.md",
        ))
    except Exception as e:  # noqa: BLE001
        report.steps.append(OnboardStep(
            name="render_report", ok=False, detail=str(e),
        ))

    return report


def render_report_md(report: OnboardReport) -> str:
    lines = [
        f"# Onboard report — `{report.vendor_id}`",
        "",
        f"_Generated:_ {report.generated_at_utc}",
        f"_Pilot folder:_ `{report.out_dir}`",
        f"_Verdict:_ {'✅ READY-TO-CALIBRATE' if report.passed else '🔴 BLOCKED'}",
        "",
        "## Steps",
        "",
        "| # | Step | Result | Detail | Artifact |",
        "|---|------|:------:|--------|----------|",
    ]
    for i, s in enumerate(report.steps, 1):
        flag = "✅" if s.ok else "🔴"
        lines.append(
            f"| {i} | `{s.name}` | {flag} | {s.detail or '—'} | "
            f"{f'`{s.artifact}`' if s.artifact else '—'} |"
        )
    lines.extend([
        "",
        "## Next steps for the vendor",
        "",
        "1. Replace the synthesized IR with a real PAR-derived IR ",
        "   (use `slot-parse <vendor> raw/` to convert the supplied ",
        "   PAR Excel into the universal IR JSON).",
        "2. Run `slot-build <ir.json> --cert` to produce a real cert ",
        "   package with MC-verified RTP.",
        "3. Run `slot-cert-verify cert.v2.xml --ir ir.json` to confirm ",
        "   the cert digest matches the IR bytes.",
        "4. Submit through `slot-multi-territory --profile <gli19> ...` ",
        "   for jurisdiction sign-off.",
    ])
    return "\n".join(lines) + "\n"
