/**
 * W6.4 — PCG-64 XSL-RR-64 TypeScript implementation.
 *
 * **Bit-identical** mirror of `rust-sim/src/rng.rs::Pcg64Backend`. Both sides
 * are pinned to the same KAT vector file (`tests/fixtures/pcg64_kat.json`)
 * which is regenerated by `cargo run --release --bin pcg64_kat_dump`.
 *
 * Why a second implementation when Mulberry32 already has TS↔Rust parity?
 *
 * 1. Mulberry32 has a 32-bit state — period 2^32 ≈ 4.3e9. For 100k-spin
 *    portfolio runs we're nowhere near that ceiling, but multi-jurisdiction
 *    1B+ MC certs (W63 exact enumeration v3, W212 perf gauntlet) burn
 *    through it in ~4.3 seconds on a single core.
 * 2. PCG-64 has a 128-bit state — period 2^126 ≈ 8.5e37. Period concerns
 *    vanish.
 * 3. UKGC RTS 7 / MGA Art. 11 audits now ask for a "BigCrush-pass /
 *    PractRand-pass" PRNG byte-for-byte across the simulator and any
 *    third-party tooling. PCG-64 passes both; Mulberry32 fails PractRand
 *    after ~2 GB of output. Having an independent TS implementation lets
 *    third-party regulators run our IRs through their own evaluator and
 *    still get the **exact same** spin sequence the Rust simulator did.
 *
 * **Implementation note** — JavaScript has no native `u128`, so we carry
 * state as `BigInt` masked to 128 bits and lift output back to `u64` (also
 * `BigInt`). The factor-of-~50× slowdown vs. native u128 is irrelevant for
 * the parity-gate use case (a few thousand draws per fixture); production
 * MC still runs in Rust.
 *
 * Reference: O'Neill, "PCG: A Family of Simple Fast Space-Efficient
 * Statistically Good Algorithms for Random Number Generation" (2014).
 * Multiplier nibble correction: Steele & Vigna 2021 (changes ...44 → ...45
 * so `a ≡ 1 (mod 4)` per Hull-Dobell — without this fix the LCG has a
 * fixed point in 64 steps and emits all-identical outputs).
 */

// ─── Constants ────────────────────────────────────────────────────────────────

const MASK_128: bigint = (1n << 128n) - 1n;
const MASK_64: bigint = (1n << 64n) - 1n;

/** Steele & Vigna 2021 multiplier — must match Rust `PCG128_MULT`. */
export const PCG64_MULT: bigint = 0x2360ed051fc65da44385df649fccef45n;

/** Default odd increment — must match Rust `PCG128_INC_DEFAULT`. */
export const PCG64_INC_DEFAULT: bigint = (0xda3e39cb94b95bdbn << 1n) | 1n;

/** SplitMix-style additive constant used in the second seed-init step. */
const GOLDEN_GAMMA: bigint = 0x9e3779b97f4a7c15n;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toBigInt64Unsigned(value: bigint): bigint {
  return value & MASK_64;
}

/** Rotate a `u64` right by `r` bits — emulates Rust `u64::rotate_right`. */
function rotr64(x: bigint, r: number): bigint {
  const rot = r & 63;
  if (rot === 0) return x & MASK_64;
  const masked = x & MASK_64;
  return ((masked >> BigInt(rot)) | (masked << BigInt(64 - rot))) & MASK_64;
}

// ─── Pcg64 backend ────────────────────────────────────────────────────────────

/**
 * PCG-64 XSL-RR-64 — 128-bit state, 64-bit output, period 2^126.
 *
 * Carry-compatible with `rust-sim/src/rng.rs::Pcg64Backend`. Seed with the
 * same `u64` on both sides and the resulting `next_u64()` stream is
 * byte-identical.
 */
export class Pcg64 {
  private state: bigint;
  private inc: bigint;

  constructor(seed: bigint | number, inc: bigint = PCG64_INC_DEFAULT) {
    if (typeof seed === "number") {
      if (!Number.isInteger(seed) || seed < 0) {
        throw new Error(`Pcg64: numeric seed must be a non-negative integer, got ${seed}`);
      }
      seed = BigInt(seed);
    }
    seed = seed & MASK_64; // narrow to u64

    // Increment must be odd (selects the LCG stream). Force the low bit.
    this.inc = (inc | 1n) & MASK_128;

    // Two-step seed initialization — identical sequence to the Rust impl.
    this.state = 0n;
    this.state = (this.state + seed) & MASK_128;
    this.advance();
    this.state = (this.state + GOLDEN_GAMMA) & MASK_128;
    this.advance();
  }

  private advance(): void {
    this.state = (this.state * PCG64_MULT + this.inc) & MASK_128;
  }

  /** Uniform 64-bit integer in `[0, 2^64)`. Returns `bigint`. */
  nextU64(): bigint {
    const old = this.state;
    this.advance();
    const hi = (old >> 64n) & MASK_64;
    const lo = old & MASK_64;
    const xs = hi ^ lo;
    // Top 6 bits of the high half give the rotation amount.
    const rot = Number((hi >> 58n) & 0x3fn);
    return rotr64(xs, rot);
  }

  /** Uniform float in `[0, 1)` — top 53 bits / 2^53 (IEEE-754 safe). */
  nextF64(): number {
    const v = this.nextU64();
    const top53 = v >> 11n;
    return Number(top53) / 2 ** 53;
  }

  /** Uniform integer in `[0, max)` with **zero modulo bias** (Lemire). */
  nextBoundedU32(max: number): number {
    if (!Number.isInteger(max) || max <= 0) {
      throw new Error(`Pcg64.nextBoundedU32: max must be positive integer, got ${max}`);
    }
    if (max === 1) return 0;
    const maxB = BigInt(max);
    // Use the upper 32 bits of the 64-bit draw — top-quality regardless of
    // the LCG's internal mixing depth, matching the Rust implementation.
    const hi32 = (v: bigint): bigint => (v >> 32n) & 0xffffffffn;
    let m = hi32(this.nextU64()) * maxB;
    let lo = m & 0xffffffffn;
    if (lo < maxB) {
      const threshold = (-maxB & MASK_64) % maxB; // wrapping_neg() % max
      while (lo < threshold) {
        m = hi32(this.nextU64()) * maxB;
        lo = m & 0xffffffffn;
      }
    }
    return Number(m >> 32n);
  }

  /** Independent stream split by xoring nonce into the increment. */
  split(nonce: bigint | number): Pcg64 {
    const nonceB = typeof nonce === "number" ? BigInt(nonce) : nonce;
    const newInc =
      (this.inc ^ ((nonceB & MASK_64) * GOLDEN_GAMMA & MASK_128)) | 1n;
    const child = new Pcg64(0n, newInc);
    // Override the seed-init state with the parent's current state so the
    // child diverges from "now", not from zero. Matches Rust split() logic.
    child.state = this.state;
    child.advance();
    return child;
  }

  /** Raw 4×u64 state (hi128, lo128, hi_inc, lo_inc) for debugging. */
  seedState(): [bigint, bigint, bigint, bigint] {
    return [
      (this.state >> 64n) & MASK_64,
      this.state & MASK_64,
      (this.inc >> 64n) & MASK_64,
      this.inc & MASK_64,
    ];
  }
}

// ─── Convenience wrappers ─────────────────────────────────────────────────────

/**
 * High-level RNG facade with the same API surface as `src/utils/rng.ts::RNG`,
 * but backed by PCG-64. Useful when an audit-grade PRNG is needed for
 * BigCrush / PractRand evidence in operator certification bundles.
 */
export class Pcg64Rng {
  private inner: Pcg64;
  private readonly initialSeed: bigint;

  constructor(seed: bigint | number) {
    const seedB = typeof seed === "number" ? BigInt(seed) : seed;
    this.initialSeed = seedB & MASK_64;
    this.inner = new Pcg64(this.initialSeed);
  }

  /** Initial seed used to construct this RNG (post-mask). */
  getSeed(): bigint {
    return this.initialSeed;
  }

  /** Uniform float in `[0, 1)`. */
  nextFloat(): number {
    return this.inner.nextF64();
  }

  /** Uniform integer in `[min, max]` inclusive. */
  nextInt(min: number, max: number): number {
    if (min > max) throw new Error("Pcg64Rng.nextInt: min must be <= max");
    const range = max - min + 1;
    return min + this.inner.nextBoundedU32(range);
  }

  /** Uniform integer in `[0, max)` exclusive. */
  nextIntExclusive(max: number): number {
    return this.inner.nextBoundedU32(max);
  }

  /** Pick a uniformly-random element from a non-empty array. */
  pick<T>(array: T[]): T {
    if (array.length === 0) throw new Error("Cannot pick from empty array");
    return array[this.inner.nextBoundedU32(array.length)];
  }

  /** Boolean Bernoulli sample with success probability `p`. */
  chance(p: number): boolean {
    if (p <= 0) return false;
    if (p >= 1) return true;
    return this.inner.nextF64() < p;
  }

  /** Clone — new RNG re-seeded from the *initial* seed, not the current state. */
  clone(): Pcg64Rng {
    return new Pcg64Rng(this.initialSeed);
  }
}
