"""P10.4 — `slot-design` CLI orchestrator.

End-to-end natural-language → IR pipeline:

    prompt → parse_prompt → prompt_to_dsl → dsl_to_ir_via_smt → IR JSON

CLI:

    python -m tools.slot_design "5×3 Vendor B-style FS + HoldAndWin" \\
                                --target-rtp 0.965 \\
                                --out games/my-game/

Output layout under --out:

    <out>/spec.json         # PromptSpec audit dump (deterministic)
    <out>/game.dsl.toml     # DSL TOML (designer hand-editable)
    <out>/<slug>.slot-sim.ir.json   # universal IR (SMT-locked optional)
    <out>/REVIEW.md         # human-readable summary + audit decisions

Exit codes:
    0  pipeline OK
    1  pipeline failure (validation / SMT / IO)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict
from pathlib import Path

from tools.slot_design.prompt_parser import (
    parse_prompt,
    prompt_to_dsl,
)
from tools.slot_design.composition_planner import plan_composition
from tools.slot_design.review_ui import emit_review_ui
from tools.slot_design.share_aware_lock import share_aware_lock


def _slugify(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", name.lower()).strip("-")
    return s or "untitled-slot"


def _try_smt_lock(dsl: dict, no_smt: bool, share_aware: bool = True) -> dict:
    """Run the W6.4 SMT-locked synthesizer if available; fallback to W6.2
    direct DSL→IR synthesizer when z3 missing or --no-smt-lock.

    When `share_aware=True` and the DSL features carry `_rtp_share_alloc`
    hints from the composition planner (P10.2), the P10.7 share-aware
    wrapper splits the target RTP across base game + feature contributions
    so the solver doesn't over-allocate.
    """
    if no_smt:
        from tools.gdd_extract.dsl import dsl_to_slot_sim_ir
        return dsl_to_slot_sim_ir(dsl)
    if share_aware:
        return share_aware_lock(dsl)
    try:
        from tools.gdd_extract.smt_synth import dsl_to_ir_via_smt
        return dsl_to_ir_via_smt(dsl)
    except Exception as exc:  # noqa: BLE001
        # Graceful fallback — clean-room reproducibility expects deterministic
        # output even when z3 missing.
        from tools.gdd_extract.dsl import dsl_to_slot_sim_ir
        ir = dsl_to_slot_sim_ir(dsl)
        if isinstance(ir.get("meta"), dict):
            notes = ir["meta"].setdefault("notes", [])
            notes.append(f"slot-design: SMT lock skipped ({exc}); deterministic fallback used.")
        return ir


def _build_review_md(spec, dsl: dict, ir: dict, out_path: Path) -> str:
    lines: list[str] = []
    lines.append(f"# slot-design Review — {dsl['meta']['name']}")
    lines.append("")
    lines.append(f"> Generated by `slot-design` from prompt:")
    lines.append(f"> `{spec.raw_prompt}`")
    lines.append("")
    lines.append("## Parsed spec")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Topology | {spec.reels}×{spec.rows} ({spec.topology_shape}, {spec.paylines} paylines/ways) |")
    lines.append(f"| Target RTP | {spec.target_rtp:.4f} |")
    lines.append(f"| Volatility | {spec.volatility} |")
    lines.append(f"| Vendor style | {spec.vendor_style} |")
    lines.append(f"| Max win cap | {spec.max_win_x}× |")
    lines.append(f"| Features detected | {', '.join(spec.feature_kinds) or '(none)'} |")
    lines.append("")
    lines.append("## Detection audit log")
    lines.append("")
    for entry in spec.audit_log:
        lines.append(f"- {entry}")
    lines.append("")
    lines.append("## Output files")
    lines.append("")
    lines.append(f"- `spec.json` — PromptSpec dataclass dump")
    lines.append(f"- `game.dsl.toml` — DSL hand-editable spec")
    lines.append(f"- `{_slugify(dsl['meta']['name'])}.slot-sim.ir.json` — universal IR")
    lines.append(f"- `REVIEW.md` — this report")
    lines.append("")
    lines.append("## Next steps")
    lines.append("")
    lines.append("1. Review `game.dsl.toml`, hand-edit feature params if needed.")
    lines.append("2. Re-run `slot-design --from-dsl game.dsl.toml --out .` to re-lock.")
    lines.append("3. `slot-build <out>/spec.json --codegen-rust` for Rust scaffold.")
    lines.append("4. `slot-build <out>/spec.json --cert-package <out>/cert.zip` for cert.")
    return "\n".join(lines)


def _dump_dsl_toml(dsl: dict) -> str:
    """Tiny TOML emitter — avoids new dependency. Handles only the shapes
    `prompt_to_dsl` emits (no nested tables-of-tables beyond features list)."""
    out: list[str] = []
    out.append("[meta]")
    for k, v in dsl["meta"].items():
        if isinstance(v, list):
            if v and isinstance(v[0], str):
                rendered = ", ".join(f'"{x}"' for x in v)
            else:
                rendered = ", ".join(str(x) for x in v)
            out.append(f"{k} = [{rendered}]")
        elif isinstance(v, str):
            out.append(f'{k} = "{v}"')
        else:
            out.append(f"{k} = {v}")
    out.append("")
    out.append("[topology]")
    for k, v in dsl["topology"].items():
        if isinstance(v, str):
            out.append(f'{k} = "{v}"')
        else:
            out.append(f"{k} = {v}")
    out.append("")
    out.append("[bet_table]")
    bt = dsl["bet_table"]
    out.append(f"min_bet = {bt['min_bet']}")
    out.append(f"max_bet = {bt['max_bet']}")
    out.append(f"multipliers = [{', '.join(str(x) for x in bt['multipliers'])}]")
    out.append("")
    for feat in dsl.get("features", []):
        out.append("[[features]]")
        for k, v in feat.items():
            if isinstance(v, list):
                if v and isinstance(v[0], str):
                    rendered = ", ".join(f'"{x}"' for x in v)
                else:
                    rendered = ", ".join(str(x) for x in v)
                out.append(f"{k} = [{rendered}]")
            elif isinstance(v, str):
                out.append(f'{k} = "{v}"')
            else:
                out.append(f"{k} = {v}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def run(args: argparse.Namespace) -> int:
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    target_rtp = args.target_rtp if args.target_rtp is not None else None

    if args.from_dsl:
        # Bypass NL parser; load DSL TOML directly. Useful for designer re-run.
        import tomllib
        with open(args.from_dsl, "rb") as fp:
            dsl = tomllib.load(fp)
        spec = None
    else:
        spec = parse_prompt(args.prompt, target_rtp=target_rtp)
        dsl = prompt_to_dsl(spec)

    # Apply optional flags
    if args.volatility:
        dsl["meta"]["target_volatility"] = args.volatility
    if args.max_win_x:
        dsl["meta"]["max_win_x"] = args.max_win_x

    # ── P10.2 — composition planner balances feature RTP shares ──────
    if not args.no_plan_composition:
        audit_log = dsl.setdefault("meta", {}).setdefault("design_audit", [])
        if not isinstance(audit_log, list):
            audit_log = []
            dsl["meta"]["design_audit"] = audit_log
        plan_composition(dsl, audit=audit_log)

    # Persist spec audit dump
    if spec is not None:
        spec_dict = asdict(spec)
        with (out_dir / "spec.json").open("w") as fp:
            json.dump(spec_dict, fp, indent=2)

    # Persist DSL TOML
    dsl_toml_path = out_dir / "game.dsl.toml"
    dsl_toml_path.write_text(_dump_dsl_toml(dsl))

    # Build IR (SMT-locked or fallback; share-aware by default)
    ir = _try_smt_lock(
        dsl,
        args.no_smt_lock,
        share_aware=not args.no_share_aware,
    )
    slug = _slugify(dsl["meta"]["name"])
    ir_path = out_dir / f"{slug}.slot-sim.ir.json"
    with ir_path.open("w") as fp:
        json.dump(ir, fp, indent=2)

    # Human-readable review
    if spec is not None:
        review_md = _build_review_md(spec, dsl, ir, out_dir)
        (out_dir / "REVIEW.md").write_text(review_md)

    # P10.3 — Studio review UI (always emit; no host dep)
    if not args.no_review_ui:
        emit_review_ui(out_dir)

    # ── P10.6 — optional cert-pack glue ────────────────────────────────
    cert_xml_path: Path | None = None
    cert_zip_path: Path | None = None
    if args.cert_xml or args.cert_pack:
        try:
            from tools.slot_build.cert_xml import emit_cert_xml
            cert_xml_path = out_dir / f"{slug}.cert.xml"
            emit_cert_xml(ir, cert_xml_path)
        except Exception as exc:  # noqa: BLE001
            if not args.quiet:
                print(f"[slot-design] WARN cert-xml emit failed: {exc}", file=sys.stderr)
            cert_xml_path = None

    if args.cert_pack:
        try:
            from tools.slot_build.cert_package import build_cert_package
            cert_zip_path = build_cert_package(
                out_dir=out_dir,
                game_id=slug,
                swid=str(args.swid or "001"),
                vendor=str(dsl["meta"].get("vendor_style", "generic")),
                universal_ir_path=ir_path,
            )
        except Exception as exc:  # noqa: BLE001
            if not args.quiet:
                print(f"[slot-design] WARN cert-pack emit failed: {exc}", file=sys.stderr)
            cert_zip_path = None

    if not args.quiet:
        print(f"[slot-design] OK · prompt → IR · out={out_dir}")
        if spec is not None:
            print(f"  features detected: {', '.join(spec.feature_kinds) or '(none)'}")
            print(f"  target_rtp: {spec.target_rtp:.4f}")
        print(f"  ir: {ir_path}")
        print(f"  dsl: {dsl_toml_path}")
        if cert_xml_path:
            print(f"  cert-xml: {cert_xml_path}")
        if cert_zip_path:
            print(f"  cert-pack: {cert_zip_path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="slot-design",
        description="P10 — natural-language → IR pipeline.",
    )
    parser.add_argument("prompt", nargs="?",
                        help="Free-form game description (omit if using --from-dsl).")
    parser.add_argument("--out", required=True,
                        help="Output directory.")
    parser.add_argument("--target-rtp", type=float, default=None,
                        help="Override target RTP from prompt (e.g. 0.965).")
    parser.add_argument("--volatility", default=None,
                        choices=["low", "medium", "high", "ultra"],
                        help="Override volatility from prompt.")
    parser.add_argument("--max-win-x", type=int, default=None,
                        help="Override max-win cap from prompt.")
    parser.add_argument("--from-dsl",
                        help="Skip NL parser; load DSL TOML directly.")
    parser.add_argument("--no-smt-lock", action="store_true",
                        help="Skip SMT-locked RTP synthesis (deterministic fallback).")
    parser.add_argument("--no-share-aware", action="store_true",
                        help="Skip P10.7 share-aware lock (use plain W6.4).")
    parser.add_argument("--no-plan-composition", action="store_true",
                        help="Skip P10.2 composition planner (raw template DSL).")
    parser.add_argument("--no-review-ui", action="store_true",
                        help="Skip P10.3 review.html + review.js emit.")
    parser.add_argument("--cert-xml", action="store_true",
                        help="Emit regulator-shape cert XML alongside IR.")
    parser.add_argument("--cert-pack", action="store_true",
                        help="Emit signed cert ZIP (implies --cert-xml).")
    parser.add_argument("--swid", default=None,
                        help="SWID for cert manifest (default: 001).")
    parser.add_argument("--quiet", action="store_true",
                        help="Suppress non-error output.")
    args = parser.parse_args(argv)

    if not args.prompt and not args.from_dsl:
        parser.error("either a prompt or --from-dsl must be provided")

    return run(args)


if __name__ == "__main__":
    sys.exit(main())
