"""Community contributor flow (W78 / P7.6)."""
from __future__ import annotations
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from string import Template
from typing import Any


_PR_BODY = Template(
    """## $template_id — community contribution

**Contributor**: $contributor
**Template ID**: `$template_id`
**Target RTP**: $target_rtp
**Volatility class**: $volatility
**Features**: $features

### Checklist (please tick before requesting review)

- [ ] `slot-config-validate <ir.json>` passes
- [ ] `slot-jurisdiction-check <ir.json>` passes against at least one
      profile
- [ ] `slot-ir-fuzz <ir.json>` passes I1–I7 invariants
- [ ] `slot-cert-xml-v2 <ir.json> --out cert.xml --validate` returns 0
- [ ] No vendor-identifying string in `meta.name` / `meta.notes`
      (run `slot-ir-sanitize` to redact)
- [ ] `slot-marketplace-catalog` pricing tier set deliberately

### What this template adds

$summary

### Acceptance criteria

* Lints pass on the merge gate (W11 + W56 + W58).
* Reviewer agrees the pricing tier matches feature complexity.
* `slot-master-gate` returns PASS or WARN — never FAIL.
"""
)


_CONTRIBUTING = """# CONTRIBUTING

Welcome — this folder is a starter kit for adding a new game
template to the slot math marketplace.

## What's in this folder

- `<template-id>.ir.json`  — your universal IR (edit me)
- `cert.xml`               — empty cert XML stub (regenerated by CI)
- `PR_DESCRIPTION.md`      — fill in + paste into your PR body
- `contribution-meta.json` — machine-readable provenance for the
                              merge bot
- `CONTRIBUTING.md`        — this file

## Step-by-step

```bash
# 1. Validate your IR
slot-config-validate <template-id>.ir.json

# 2. Lint against the jurisdiction you target
slot-jurisdiction-check <template-id>.ir.json --profile ukgc

# 3. Run the invariant fuzzer
slot-ir-fuzz <template-id>.ir.json --runs 1000

# 4. Emit a v2 cert and validate it
slot-cert-xml-v2 <template-id>.ir.json --out cert.xml --validate

# 5. Sanitize any vendor strings
slot-ir-sanitize <template-id>.ir.json --in-place
```

## Pricing tier guidance

| Feature kinds | Jurisdictions | Tier |
|---|---|---|
| 0–1 | 0   | FREE    |
| 2–3 | 1   | BASIC   |
| 4+  | 2+  | PREMIUM |

## Need help?

Open a draft PR — reviewers will guide you through. The W11–W74 gate
chain runs on every PR; failures are explained inline.
"""


@dataclass
class StarterParams:
    template_id: str
    contributor: str = "anonymous"
    title: str = ""
    target_rtp: float = 0.96
    volatility: str = "medium"
    reels: int = 5
    rows: int = 3
    paylines: int = 20
    features: list[str] = field(default_factory=list)
    summary: str = ""


@dataclass
class ContributionPackage:
    out_dir: Path
    ir_path: Path
    cert_xml_stub: Path
    pr_description: Path
    contributing_md: Path
    contribution_meta: Path

    def to_dict(self) -> dict[str, Any]:
        return {
            "out_dir": str(self.out_dir),
            "ir": str(self.ir_path),
            "cert_xml_stub": str(self.cert_xml_stub),
            "pr_description": str(self.pr_description),
            "contributing_md": str(self.contributing_md),
            "contribution_meta": str(self.contribution_meta),
        }


def _starter_ir(p: StarterParams) -> dict[str, Any]:
    """Minimal IR matching the universal schema."""
    return {
        "meta": {
            "id": p.template_id,
            "name": p.title or p.template_id.replace("-", " ").title(),
            "vendor": "community",
            "swid": f"COMMUNITY-{p.template_id.upper()}",
            "version": "0.1.0",
            "target_rtp": p.target_rtp,
            "notes": ["Community contribution starter — replace stubs."],
        },
        "topology": {
            "kind": "rectangular",
            "reels": p.reels,
            "rows": p.rows,
        },
        "evaluation": {
            "paylines": list(range(p.paylines)),
        },
        "limits": {"max_win_x": 5000.0},
        "features": [{"kind": k} for k in p.features],
        "symbols": [
            {"id": "S_A", "name": "A", "kind": "high"},
            {"id": "S_B", "name": "B", "kind": "low"},
            {"id": "S_WILD", "name": "Wild", "kind": "wild"},
        ],
        "reels": {"base": [["A", "B"] * 16 for _ in range(p.reels)]},
        "paytable": [
            {"combo": ["A"] * 5, "pays": 100},
            {"combo": ["A"] * 4, "pays": 50},
            {"combo": ["A"] * 3, "pays": 10},
        ],
    }


def bootstrap_contribution(
    out_dir: Path,
    params: StarterParams,
) -> ContributionPackage:
    out_dir = Path(out_dir) / params.template_id
    out_dir.mkdir(parents=True, exist_ok=True)

    ir = _starter_ir(params)
    ir_path = out_dir / f"{params.template_id}.ir.json"
    ir_path.write_text(json.dumps(ir, indent=2, sort_keys=True))

    cert_path = out_dir / "cert.xml"
    cert_path.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- generated by CI; do not hand-edit -->\n'
        '<SlotMathCert xmlns="urn:slotmath:cert:v2" cert_version="2.0"/>\n'
    )

    pr_path = out_dir / "PR_DESCRIPTION.md"
    pr_path.write_text(_PR_BODY.substitute(
        template_id=params.template_id,
        contributor=params.contributor,
        target_rtp=f"{params.target_rtp:.2%}",
        volatility=params.volatility,
        features=", ".join(params.features) or "—",
        summary=params.summary or "(describe the template here)",
    ))

    contrib_path = out_dir / "CONTRIBUTING.md"
    contrib_path.write_text(_CONTRIBUTING)

    meta_path = out_dir / "contribution-meta.json"
    meta_path.write_text(json.dumps({
        "template_id": params.template_id,
        "contributor": params.contributor,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "starter_params": asdict(params),
    }, indent=2, sort_keys=True))

    return ContributionPackage(
        out_dir=out_dir,
        ir_path=ir_path,
        cert_xml_stub=cert_path,
        pr_description=pr_path,
        contributing_md=contrib_path,
        contribution_meta=meta_path,
    )
