#!/usr/bin/env python3
"""W244 wave 72 — auto-generate `docs/README.md` index.

83 standalone docs files u `docs/*.md` + 20 kernel reference docs u
`docs/kernels/` — bez entry point fajla. GitHub default kad otvoriš
`docs/` dir prikazuje sve fajlove ravno, bez kategorija ili preview-a.

Ovaj generator čita prvi `# Heading` (ako postoji) i prvu non-empty
liniju iz svakog docs/*.md fajla, kategoriše po naming prefix (npr.
"BACKEND_*" = backend, "GAAS_*" = GaaS, etc), i piše deterministic
`docs/README.md` index.

Output: `docs/README.md` — deterministic, byte-stable.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"
OUT = DOCS / "README.md"

# Category map by filename prefix → human-readable name.
# Order matters — earlier entries take priority on match.
CATEGORIES: list[tuple[str, str]] = [
    ("KERNELS", "Kernel references (closed-form math)"),
    ("BACKEND_", "Backend / API"),
    ("GAAS_", "GaaS (Gaming-as-a-Service)"),
    ("RNG_", "RNG / cryptographic primitives"),
    ("DATABASE", "Database / persistence"),
    ("DEPLOYMENT", "Deployment"),
    ("DR_", "Disaster recovery"),
    ("DISASTER", "Disaster recovery"),
    ("CERT_", "Certification / regulator"),
    ("CSM_", "CSM (Customer Success)"),
    ("COMMERCIAL_", "Commercial / sales"),
    ("DEMO_", "Demo theater"),
    ("DEVELOPER_", "Developer guide"),
    ("ANALYTICS", "Analytics / RTP drift"),
    ("CHAOS_", "Chaos engineering / resilience"),
    ("CONTINUOUS_", "Continuous hardening"),
    ("DEPENDENCY_", "Dependency upgrades"),
    ("FUZZ_", "Fuzz testing"),
    ("HSM_", "HSM / security"),
    ("I18N", "Internationalization"),
]


def _categorize(stem: str) -> tuple[str, int]:
    """Return (category, priority) — priority for stable group sort."""
    for i, (prefix, name) in enumerate(CATEGORIES):
        if stem.upper().startswith(prefix):
            return name, i
    return "Other / uncategorized", len(CATEGORIES)


def _extract_title_and_preview(path: Path) -> tuple[str, str]:
    """Return (title, preview). Title from first `# H`, preview = next
    non-empty non-heading line."""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (UnicodeDecodeError, OSError):
        return (path.stem, "")
    title = path.stem
    preview = ""
    for line in lines:
        s = line.strip()
        if not title or title == path.stem:
            m = re.match(r"^#\s+(.+?)\s*$", s)
            if m:
                title = m.group(1)
                continue
        if s and not s.startswith("#") and not preview:
            # Strip Markdown link syntax + code ticks for preview
            preview = re.sub(r"`([^`]+)`", r"\1", s)
            preview = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", preview)
            preview = preview[:140]
        if title and preview:
            break
    return title, preview


def main() -> int:
    if not DOCS.is_dir():
        print(f"[docs-index] missing dir: {DOCS}")
        return 1

    md_files = sorted(DOCS.glob("*.md"))
    # Exclude the output file itself from indexing.
    md_files = [f for f in md_files if f.name != "README.md"]

    # Also include kernel docs (sub-dir)
    kernel_md = sorted((DOCS / "kernels").glob("*.md"))
    kernel_md = [f for f in kernel_md if f.name != "README.md"]

    # Group by category
    groups: dict[tuple[int, str], list[tuple[Path, str, str]]] = {}
    for f in md_files:
        cat, prio = _categorize(f.stem)
        title, preview = _extract_title_and_preview(f)
        groups.setdefault((prio, cat), []).append((f, title, preview))

    # Build markdown
    lines = [
        "# `slot-math-engine-template` — docs index",
        "",
        "Auto-generated by `tools/build_docs_index.py`. Do not edit by hand.",
        "",
        f"**Total docs:** {len(md_files) + len(kernel_md)} "
        f"({len(md_files)} top-level + {len(kernel_md)} kernel references)",
        "",
        "## Categories",
        "",
    ]

    # Insert categories in priority order
    for (prio, cat) in sorted(groups.keys()):
        entries = groups[(prio, cat)]
        lines.append(f"### {cat} ({len(entries)})")
        lines.append("")
        for f, title, preview in entries:
            href = f.name
            if preview:
                lines.append(f"- [{title}]({href}) — {preview}")
            else:
                lines.append(f"- [{title}]({href})")
        lines.append("")

    # Kernel docs as separate top-level section
    if kernel_md:
        lines.append(f"### Kernel reference docs ({len(kernel_md)})")
        lines.append("")
        lines.append(
            "Per-kernel auditor-facing Markdown with LaTeX formulas. "
            "See [kernels/README.md](kernels/README.md) for the per-kernel index."
        )
        lines.append("")
        for f in kernel_md:
            title, _ = _extract_title_and_preview(f)
            lines.append(f"- [{title}](kernels/{f.name})")
        lines.append("")

    # Footer with rebuild recipe
    lines.append("---")
    lines.append("")
    lines.append("Rebuild:")
    lines.append("```bash")
    lines.append("python3 tools/build_docs_index.py")
    lines.append("```")
    lines.append("")

    text = "\n".join(lines)

    # Compute index Merkle for deterministic verification
    merkle = hashlib.sha256(text.encode("utf-8")).hexdigest()
    text += f"\nIndex Merkle (SHA-256): `{merkle}`\n"

    OUT.write_text(text, encoding="utf-8")
    print(f"[docs-index] wrote {OUT.relative_to(REPO)}")
    print(f"  top-level docs:  {len(md_files)}")
    print(f"  kernel docs:     {len(kernel_md)}")
    print(f"  categories:      {len(groups)}")
    print(f"  index merkle:    {merkle}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
