"""PHASE 44 — Build audit harness.

Composes the three agents into one `BuildAuditReport` + emits a
regulator-friendly Markdown summary alongside the per-agent JSON.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from tools.build_audit.button_auditor import (
    audit_build_buttons,
)
from tools.build_audit.math_auditor import (
    audit_math_algorithms,
)
from tools.build_audit.weight_auditor import (
    audit_weight_precision,
)


SCHEMA = "urn:slotmath:build-audit:v1"


@dataclass
class BuildAuditReport:
    schema: str
    audited_at: str
    repo_root: str
    buttons: list[dict[str, Any]] = field(default_factory=list)
    weight_checks: list[dict[str, Any]] = field(default_factory=list)
    math_checks: list[dict[str, Any]] = field(default_factory=list)
    summary: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_markdown(self) -> str:
        s = self.summary
        out = [
            "# Build Section Audit",
            "",
            f"> Generated by `tools.build_audit` at `{self.audited_at}`",
            "> Schema: `{}`".format(self.schema),
            "",
            "## Overall verdict",
            "",
            "| Layer | Pass | Warn | Fail | Verdict |",
            "|---|---:|---:|---:|---|",
            (
                f"| Buttons | {s.get('buttons_pass', 0)} | "
                f"{s.get('buttons_warn', 0)} | "
                f"{s.get('buttons_fail', 0)} | "
                f"**{s.get('buttons_verdict', '—')}** |"
            ),
            (
                f"| Weight precision | {s.get('weight_pass', 0)} | "
                f"{s.get('weight_warn', 0)} | "
                f"{s.get('weight_fail', 0)} | "
                f"**{s.get('weight_verdict', '—')}** |"
            ),
            (
                f"| Math algorithms | {s.get('math_pass', 0)} | "
                f"{s.get('math_warn', 0)} | "
                f"{s.get('math_fail', 0)} | "
                f"**{s.get('math_verdict', '—')}** |"
            ),
            "",
            f"**Final verdict: `{s.get('overall_verdict', '—')}`**",
            "",
            "## Build buttons",
            "",
            "| Button | Element | Wired | A11y | Silent catch | Verdict |",
            "|---|:---:|:---:|:---:|:---:|:---:|",
        ]
        for b in self.buttons:
            out.append(
                "| `{button_id}` | {el} | {wired} | {a11y} | {silent} | **{v}** |".format(
                    button_id=b["button_id"],
                    el="✅" if b["element_found"] else "❌",
                    wired="✅" if b["handler_reachable"] else "❌",
                    a11y="✅" if b["accessibility_ok"] else "⚠️",
                    silent="❌" if b["handler_silent_catch"] else "✅",
                    v=b["verdict"],
                )
            )
        out += ["", "## Weight precision checks", "",
                "| Check | Measured | Reference | Drift | Tol | Verdict |",
                "|---|---:|---:|---:|---:|:---:|"]
        for w in self.weight_checks:
            out.append(
                "| `{cid}` | {m} | {r} | {d} | {tol} | **{v}** |".format(
                    cid=w["check_id"],
                    m=f"{w['measured']:.6g}" if w.get("measured") is not None else "—",
                    r=f"{w['reference']:.6g}" if w.get("reference") is not None else "—",
                    d=f"{w['drift']:.2e}" if w.get("drift") is not None else "—",
                    tol=f"{w['tolerance']:.0e}",
                    v=w["verdict"],
                )
            )
        out += ["", "## Math algorithm checks", "",
                "| Algorithm | Engine | Reference | Drift | Tol | Source | Verdict |",
                "|---|---:|---:|---:|---:|---|:---:|"]
        for m in self.math_checks:
            out.append(
                "| `{a}` | {ev} | {rv} | {d} | {tol} | {src} | **{v}** |".format(
                    a=m["algorithm"],
                    ev=f"{m['engine_value']:.6g}" if m.get("engine_value") is not None else "—",
                    rv=f"{m['reference_value']:.6g}" if m.get("reference_value") is not None else "—",
                    d=f"{m['drift']:.2e}" if m.get("drift") is not None else "—",
                    tol=f"{m['tolerance']:.0e}",
                    src=m["formula_source"],
                    v=m["verdict"],
                )
            )
        return "\n".join(out) + "\n"


def _aggregate_verdict(findings: list[dict[str, Any]]) -> tuple[int, int, int, str]:
    p = sum(1 for f in findings if f["verdict"] == "PASS")
    w = sum(1 for f in findings if f["verdict"] == "WARN")
    fa = sum(1 for f in findings if f["verdict"] == "FAIL")
    if fa > 0:
        v = "FAIL"
    elif w > 0:
        v = "WARN"
    else:
        v = "PASS"
    return p, w, fa, v


def run_full_audit(
    repo_root: Path | str,
    *,
    out_dir: Path | str | None = None,
) -> BuildAuditReport:
    repo = Path(repo_root)
    btn_findings = [b.to_dict() for b in audit_build_buttons(repo)]
    weight_findings = [c.to_dict() for c in audit_weight_precision(repo)]
    math_findings = [m.to_dict() for m in audit_math_algorithms()]

    b_p, b_w, b_f, b_v = _aggregate_verdict(btn_findings)
    w_p, w_w, w_f, w_v = _aggregate_verdict(weight_findings)
    m_p, m_w, m_f, m_v = _aggregate_verdict(math_findings)
    overall = (
        "FAIL"
        if "FAIL" in (b_v, w_v, m_v)
        else ("WARN" if "WARN" in (b_v, w_v, m_v) else "PASS")
    )

    report = BuildAuditReport(
        schema=SCHEMA,
        audited_at=datetime.now(timezone.utc).isoformat(),
        repo_root=str(repo),
        buttons=btn_findings,
        weight_checks=weight_findings,
        math_checks=math_findings,
        summary={
            "buttons_pass": b_p, "buttons_warn": b_w, "buttons_fail": b_f, "buttons_verdict": b_v,
            "weight_pass": w_p, "weight_warn": w_w, "weight_fail": w_f, "weight_verdict": w_v,
            "math_pass": m_p, "math_warn": m_w, "math_fail": m_f, "math_verdict": m_v,
            "overall_verdict": overall,
        },
    )

    if out_dir is not None:
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        (out / "audit.json").write_text(
            json.dumps(report.to_dict(), indent=2),
            encoding="utf-8",
        )
        (out / "SUMMARY.md").write_text(report.to_markdown(), encoding="utf-8")

    return report
